# Generated by Django 4.2.29 on 2026-03-12 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametres', '0002_typedocument_data'),
        ('pedagogie', '0002_alter_resultat_unique_together_moyennegenerale'),
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteParascolaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'activité")),
                ('type_activite', models.CharField(choices=[('SPORT', 'Sport'), ('CLUB', 'Club / Association'), ('ART', 'Art & Culture'), ('ACADEMIQUE', 'Académique'), ('AUTRE', 'Autre')], default='CLUB', max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('capacite_max', models.PositiveIntegerField(default=30, verbose_name='Capacité max')),
                ('jour_reunion', models.IntegerField(blank=True, choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')], null=True, verbose_name='Jour de réunion')),
                ('heure_debut', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites_parascolaires', to='parametres.anneescolaire', verbose_name='Année scolaire')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Activité parascolaire',
                'verbose_name_plural': 'Activités parascolaires',
                'ordering': ['type_activite', 'nom'],
                'unique_together': {('annee_scolaire', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='ConseilClasse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('date_conseil', models.DateField(verbose_name='Date du conseil')),
                ('observations', models.TextField(blank=True, verbose_name='Observations générales')),
                ('tenu', models.BooleanField(default=False, verbose_name='Conseil tenu')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conseils_classe', to='parametres.classe', verbose_name='Classe')),
                ('president', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conseils_presides', to=settings.AUTH_USER_MODEL, verbose_name='Président du conseil')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conseils_classe', to='pedagogie.trimestre', verbose_name='Trimestre')),
            ],
            options={
                'verbose_name': 'Conseil de classe',
                'verbose_name_plural': 'Conseils de classe',
                'ordering': ['-date_conseil'],
                'unique_together': {('classe', 'trimestre')},
            },
        ),
        migrations.CreateModel(
            name='SanctionDisciplinaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('type_sanction', models.CharField(choices=[('AVERTISSEMENT', 'Avertissement'), ('BLAME', 'Blâme'), ('EXCLUSION_TEMP', 'Exclusion temporaire'), ('EXCLUSION_DEF', 'Exclusion définitive'), ('TRAVAUX', "Travaux d'utilité scolaire"), ('CONVOC_PARENTS', 'Convocation des parents')], max_length=20, verbose_name='Type de sanction')),
                ('date_sanction', models.DateField(verbose_name='Date de la sanction')),
                ('motif', models.TextField(verbose_name='Motif')),
                ('duree_jours', models.PositiveIntegerField(default=0, help_text='Pour les exclusions temporaires', verbose_name='Durée (jours)')),
                ('date_retour', models.DateField(blank=True, null=True, verbose_name='Date de retour prévue')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours de traitement'), ('CONFIRME', 'Confirmée'), ('ANNULE', 'Annulée'), ('LEVEE', 'Levée')], default='EN_COURS', max_length=20, verbose_name='Statut')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('parents_convoques', models.BooleanField(default=False, verbose_name='Parents convoqués')),
                ('date_convocation', models.DateField(blank=True, null=True, verbose_name='Date convocation parents')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='inscriptions.inscription', verbose_name='Élève')),
                ('prononcee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctions_prononcees', to=settings.AUTH_USER_MODEL, verbose_name='Prononcée par')),
            ],
            options={
                'verbose_name': 'Sanction disciplinaire',
                'verbose_name_plural': 'Sanctions disciplinaires',
                'ordering': ['-date_sanction'],
            },
        ),
        migrations.CreateModel(
            name='SeanceCours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('jour', models.IntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')])),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('salle', models.CharField(blank=True, max_length=50)),
                ('enseignement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='pedagogie.enseignement')),
            ],
            options={
                'verbose_name': 'Séance de cours',
                'verbose_name_plural': 'Séances de cours',
                'ordering': ['jour', 'heure_debut'],
                'unique_together': {('enseignement', 'jour', 'heure_debut')},
            },
        ),
        migrations.CreateModel(
            name='ParticipationActivite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('date_inscription', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('observations', models.CharField(blank=True, max_length=200, verbose_name='Observations')),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='viescolaire.activiteparascolaire', verbose_name='Activité')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='inscriptions.inscription', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Participation à une activité',
                'verbose_name_plural': 'Participations aux activités',
                'unique_together': {('activite', 'inscription')},
            },
        ),
        migrations.CreateModel(
            name='DecisionConseil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('decision', models.CharField(choices=[('PASSAGE', 'Passage'), ('REDOUBLEMENT', 'Redoublement'), ('ORIENTATION', 'Réorientation'), ('EXCLUSION', 'Exclusion'), ('RACHAT', 'Rachat accordé')], default='PASSAGE', max_length=20, verbose_name='Décision')),
                ('appreciation', models.TextField(blank=True, verbose_name='Appréciation')),
                ('mention_honneur', models.BooleanField(default=False, verbose_name="Mention d'honneur")),
                ('encouragements', models.BooleanField(default=False, verbose_name='Encouragements')),
                ('felicitations', models.BooleanField(default=False, verbose_name='Félicitations')),
                ('conseil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='viescolaire.conseilclasse', verbose_name='Conseil')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions_conseil', to='inscriptions.inscription', verbose_name='Inscription')),
            ],
            options={
                'verbose_name': 'Décision du conseil',
                'verbose_name_plural': 'Décisions du conseil',
                'unique_together': {('conseil', 'inscription')},
            },
        ),
    ]
