# Generated by Django 4.2.29 on 2026-03-23 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogie', '0006_add_dispense_to_resultat'),
        ('viescolaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanctiondisciplinaire',
            name='appreciation_conduite',
            field=models.CharField(blank=True, help_text='Ex : Très bonne conduite, Conduite à améliorer…', max_length=200, verbose_name='Appréciation de la conduite'),
        ),
        migrations.AddField(
            model_name='sanctiondisciplinaire',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valeur positive pour un bonus, négative pour une pénalité appliquée au total des points.', max_digits=5, verbose_name='Points (+ ajout / − retrait)'),
        ),
        migrations.AddField(
            model_name='sanctiondisciplinaire',
            name='trimestre',
            field=models.ForeignKey(blank=True, help_text='Trimestre sur lequel les points sont ajoutés ou retirés.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctions_disciplinaires', to='pedagogie.trimestre', verbose_name="Trimestre d'application"),
        ),
    ]
