# Generated by Django 4.2.29 on 2026-04-04 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0003_etablissement_created_by_etablissement_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viescolaire', '0004_activiteparascolaire_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigDiscipline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('points_depart', models.PositiveIntegerField(default=20, help_text="Nombre de points attribués à chaque élève en début d'année.", verbose_name='Capital de départ')),
                ('seuil_alerte', models.IntegerField(default=5, help_text="En-dessous de ce solde, l'élève est signalé en jaune.", verbose_name="Seuil d'alerte")),
                ('seuil_conseil', models.IntegerField(default=2, help_text="En-dessous de ce solde, l'élève doit passer devant un conseil.", verbose_name='Seuil conseil disciplinaire')),
                ('seuil_exclusion', models.IntegerField(default=0, help_text="Au-dessous ou égal à ce solde, l'exclusion est déclenchée.", verbose_name="Seuil d'exclusion")),
                ('message_alerte', models.CharField(blank=True, default="L'élève est proche du seuil d'exclusion disciplinaire.", max_length=200, verbose_name="Message d'alerte")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('etablissement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_discipline', to='etablissements.etablissement', verbose_name='Établissement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Configuration discipline',
                'verbose_name_plural': 'Configurations discipline',
            },
        ),
    ]
