# Generated by Django 4.2.29 on 2026-04-05 06:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viescolaire', '0005_configdiscipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppelDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('motif', models.TextField(verbose_name='Motif de la contestation')),
                ('date_depot', models.DateField(default=datetime.date.today, verbose_name='Date de dépôt')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_INSTRUCTION', 'En instruction'), ('TRAITE', 'Traité')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('issue', models.CharField(blank=True, choices=[('MAINTENU', 'Décision maintenue'), ('MODIFIE', 'Décision modifiée'), ('ANNULE', 'Décision annulée')], max_length=15, null=True, verbose_name='Issue')),
                ('nouvelle_decision', models.CharField(blank=True, choices=[('PASSAGE', 'Passage'), ('REDOUBLEMENT', 'Redoublement'), ('ORIENTATION', 'Réorientation'), ('EXCLUSION', 'Exclusion'), ('RACHAT', 'Rachat accordé')], max_length=20, null=True, verbose_name='Nouvelle décision (si modifiée)')),
                ('observations_commission', models.TextField(blank=True, verbose_name='Observations de la commission')),
                ('date_traitement', models.DateField(blank=True, null=True, verbose_name='Date de traitement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('decision_conseil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appel', to='viescolaire.decisionconseil', verbose_name='Décision contestée')),
                ('depose_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appels_deposes', to=settings.AUTH_USER_MODEL, verbose_name='Déposé par')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appels_traites', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Appel de décision',
                'verbose_name_plural': 'Appels de décision',
                'ordering': ['-date_depot'],
            },
        ),
    ]
