# Generated by Django 4.2.29 on 2026-04-03 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date/Heure')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression')], max_length=10, verbose_name='Action')),
                ('app_label', models.CharField(max_length=50, verbose_name='Application')),
                ('model_name', models.CharField(max_length=100, verbose_name='Modèle')),
                ('object_id', models.UUIDField(verbose_name="ID de l'objet")),
                ('object_repr', models.CharField(max_length=200, verbose_name='Objet')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Modifications')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='core_auditl_timesta_189a84_idx'), models.Index(fields=['app_label', 'model_name'], name='core_auditl_app_lab_2f0dea_idx'), models.Index(fields=['user', '-timestamp'], name='core_auditl_user_id_2a1528_idx')],
            },
        ),
    ]
