# Generated by Django 5.2 — audit append-only et contexte de sécurité

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_notification_sms_envoye'),
        ('etablissements', '0004_groupe_etablissements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date/Heure'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('EXPORT', 'Export'), ('LOGIN', 'Connexion'), ('LOGIN_FAILED', 'Échec de connexion'), ('SECURITY', 'Événement de sécurité')], max_length=20, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(max_length=64, verbose_name="ID de l'objet"),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='entry_hash',
            field=models.CharField(blank=True, default='', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='etablissements.etablissement', verbose_name='Établissement'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='previous_hash',
            field=models.CharField(blank=True, default='', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='reason',
            field=models.TextField(blank=True, default='', verbose_name='Motif'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Requête'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='source',
            field=models.CharField(default='HTTP', max_length=30, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Navigateur'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['etablissement', '-timestamp'], name='core_auditl_etab_ts_idx'),
        ),
    ]
