# Generated by Django 4.2.29 on 2026-03-11 22:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametres', '__first__'),
        ('etablissements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembrePersonnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('matricule', models.CharField(help_text='Format: PERS-{ETAB}-{ANNEE}-{SEQ:04d}', max_length=20, unique=True, verbose_name='Matricule')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom(s)')),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Genre')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=200, verbose_name='Lieu de naissance')),
                ('nationalite', models.CharField(default='Burkinabè', max_length=100, verbose_name='Nationalité')),
                ('telephone', models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Adresse email')),
                ('adresse', models.TextField(blank=True, default='', verbose_name='Adresse complète')),
                ('numero_cni', models.CharField(blank=True, default='', max_length=50, verbose_name='Numéro CNI / Passport / N° Extrait')),
                ('fonction', models.CharField(max_length=100, verbose_name='Fonction/Titre')),
                ('date_embauche', models.DateField(verbose_name="Date d'embauche")),
                ('est_contractuel', models.BooleanField(default=False, verbose_name='Personnel contractuel')),
                ('est_vacataire', models.BooleanField(default=False, verbose_name='Professeur vacataire')),
                ('est_directeur', models.BooleanField(default=False, help_text="Cocher si ce membre est le directeur de l'établissement", verbose_name='Directeur/Proviseur')),
                ('est_censeur', models.BooleanField(default=False, help_text='Cocher si ce membre est censeur ou proviseur adjoint', verbose_name='Censeur/Proviseur adjoint')),
                ('situation_matrimoniale', models.CharField(choices=[('CELIBATAIRE', 'Célibataire'), ('MARIE', 'Marié(e)'), ('DIVORCE', 'Divorcé(e)'), ('VEUF', 'Veuf/Veuve')], default='CELIBATAIRE', max_length=20, verbose_name='Situation matrimoniale')),
                ('nombre_enfants', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Nombre d'enfants à charge")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='personnel/photos/', verbose_name="Photo d'identité")),
                ('poste_principal_code', models.CharField(blank=True, default='', help_text='Code du poste principal (temporaire)', max_length=20, verbose_name='Code Poste')),
                ('cycles', models.ManyToManyField(blank=True, related_name='personnel', to='parametres.cycle', verbose_name="Cycles d'enseignement")),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='etablissements.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Membre du Personnel',
                'verbose_name_plural': 'Membres du Personnel',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionPersonnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Inscription active')),
                ('date_inscription', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début de fonction')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin de fonction')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observations')),
                ('heures_hebdomadaires', models.DecimalField(decimal_places=2, default=0, help_text='Pour les professeurs vacataires', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)], verbose_name='Heures hebdomadaires')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_personnel', to='parametres.anneescolaire', verbose_name='Année scolaire')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_personnel', to='parametres.cycle', verbose_name="Cycle d'affectation")),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='personnel.membrepersonnel', verbose_name='Membre du personnel')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='parametres.poste', verbose_name='Poste occupé')),
            ],
            options={
                'verbose_name': 'Inscription Personnel',
                'verbose_name_plural': 'Inscriptions Personnel',
                'ordering': ['-annee_scolaire', 'personnel__nom'],
                'unique_together': {('personnel', 'annee_scolaire', 'cycle')},
            },
        ),
    ]
