# Generated by Django 4.2.29 on 2026-03-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membrepersonnel',
            name='matricule',
            field=models.CharField(blank=True, default='', help_text='Format: PERS-{ETAB}-{ANNEE}-{SEQ:04d}', max_length=30, unique=True, verbose_name='Matricule'),
        ),
    ]
