# Generated by Django 4.2.29 on 2026-04-09 01:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personnel', '0006_add_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membrepersonnel',
            name='numero_cni',
        ),
        migrations.AddField(
            model_name='membrepersonnel',
            name='_numero_cni_encrypted',
            field=models.CharField(blank=True, db_column='numero_cni_encrypted', default='', max_length=100, verbose_name='Numéro CNI (chiffré)'),
        ),
        migrations.AlterField(
            model_name='congepersonnel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='congepersonnel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant'),
        ),
        migrations.AlterField(
            model_name='congepersonnel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='congepersonnel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='congepersonnel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AlterField(
            model_name='salairepersonnel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='salairepersonnel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant'),
        ),
        migrations.AlterField(
            model_name='salairepersonnel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='salairepersonnel',
            name='prime_anciennete',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Calculée automatiquement ou saisie manuellement', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Prime d'ancienneté (FCFA)"),
        ),
        migrations.AlterField(
            model_name='salairepersonnel',
            name='retenue_cnss',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Cotisation sociale employé', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Retenue CNSS (FCFA)'),
        ),
        migrations.AlterField(
            model_name='salairepersonnel',
            name='retenue_iuts',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Impôt unique sur les traitements et salaires', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Retenue IUTS (FCFA)'),
        ),
        migrations.AlterField(
            model_name='salairepersonnel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='salairepersonnel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
    ]
