# Generated by Django 4.2.29 on 2026-09-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0007_remove_membrepersonnel_numero_cni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membrepersonnel',
            name='matricule',
            field=models.CharField(blank=True, default='', help_text='Format: {CODE_ETAB}-P-{ANNEE}-{SEQ}', max_length=30, unique=True, verbose_name='Matricule'),
        ),
    ]
