# Generated by Django 4.2.29 on 2026-03-11 22:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametres', '0002_typedocument_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('matricule', models.CharField(help_text='Format: BF-{REGION}-{ANNEE}-{SEQ:04d}', max_length=20, unique=True, verbose_name='Matricule')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom(s)')),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Genre')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=200, verbose_name='Lieu de naissance')),
                ('nationalite', models.CharField(default='Burkinabè', max_length=100, verbose_name='Nationalité')),
                ('pays_residence', models.CharField(default='Burkina Faso', max_length=100, verbose_name='Pays de résidence')),
                ('province', models.CharField(blank=True, default='', max_length=100, verbose_name='Province')),
                ('commune', models.CharField(blank=True, default='', max_length=100, verbose_name='Commune')),
                ('village', models.CharField(blank=True, default='', max_length=100, verbose_name='Village/Ville')),
                ('telephone_urgence', models.CharField(blank=True, default='', max_length=20, verbose_name="Téléphone d'urgence")),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Adresse email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='eleves/photos/', verbose_name="Photo d'identité")),
                ('nom_pere', models.CharField(blank=True, default='', max_length=150, verbose_name='Nom du père')),
                ('profession_pere', models.CharField(blank=True, default='', max_length=100, verbose_name='Profession du père')),
                ('nom_mere', models.CharField(blank=True, default='', max_length=150, verbose_name='Nom de la mère')),
                ('profession_mere', models.CharField(blank=True, default='', max_length=100, verbose_name='Profession de la mère')),
                ('telephone_parent', models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone des parents')),
                ('tuteur_nom', models.CharField(blank=True, default='', max_length=150, verbose_name='Nom du tuteur')),
                ('tuteur_telephone', models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone du tuteur')),
                ('tuteur_adresse', models.TextField(blank=True, default='', verbose_name='Adresse du tuteur')),
                ('etablissement_origine', models.CharField(blank=True, default='', max_length=200, verbose_name="Établissement d'origine")),
                ('last_annee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves_derniers', to='parametres.anneescolaire', verbose_name='Dernière année scolaire')),
                ('last_classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anciens_eleves', to='parametres.classe', verbose_name='Dernière classe fréquentée')),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('date_inscription', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('statut', models.CharField(choices=[('AFFECTE', 'Affecté'), ('NON_AFFECTE', 'Non affecté'), ('BOURSIER', 'Boursier'), ('EXONERE', 'Exonéré')], default='AFFECTE', max_length=20, verbose_name='Statut')),
                ('est_redoublant', models.BooleanField(default=False, verbose_name='Redoublant')),
                ('numero_recu', models.CharField(blank=True, default='', max_length=50, verbose_name='Numéro de reçu')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant payé')),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='Date du paiement')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observations')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='parametres.anneescolaire', verbose_name='Année scolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='parametres.classe', verbose_name='Classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='inscriptions.eleve', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-annee_scolaire', 'eleve__nom', 'eleve__prenom'],
                'unique_together': {('eleve', 'annee_scolaire')},
            },
        ),
    ]
