# Generated by Django 4.2.29 on 2026-03-13 19:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0008_typesanction'),
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='classe_redoublee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redoublements', to='parametres.classe', verbose_name='Classe redoublée'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='est_exonere',
            field=models.BooleanField(default=False, verbose_name='Exonéré'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='raison_exoneration',
            field=models.TextField(blank=True, default='', verbose_name="Raison d'exonération"),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='date_inscription',
            field=models.DateField(default=datetime.date.today, verbose_name="Date d'inscription"),
        ),
    ]
