# Generated by Django 4.2.29 on 2026-03-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0002_add_exonere_redoublee_date_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='classe_redoublee',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Classe redoublée'),
        ),
    ]
