# Generated by Django 4.2.29 on 2026-03-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0003_classe_redoublee_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='classe',
            field=models.CharField(max_length=100, verbose_name='Classe'),
        ),
    ]
