# Generated by Django 4.2.29 on 2026-03-13 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0008_typesanction'),
        ('inscriptions', '0004_classe_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='parametres.classe', verbose_name='Classe'),
        ),
    ]
