# Generated by Django 4.2.29 on 2026-03-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0005_revert_classe_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='date_paiement',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='montant_paye',
        ),
    ]
