# Generated by Django 4.2.29 on 2026-03-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0006_remove_montant_paye_date_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='last_classe',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Dernière classe fréquentée'),
        ),
    ]
