# Generated by Django 4.2.29 on 2026-03-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0009_last_annee_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='statut',
            field=models.CharField(choices=[('AFFECTE', 'Affecté'), ('NON_AFFECTE', 'Non affecté'), ('BOURSIER', 'Boursier'), ('EXONERE', 'Exonéré'), ('ABANDON', 'Abandon')], default='AFFECTE', max_length=20, verbose_name='Statut'),
        ),
    ]
