# Generated by Django 4.2.29 on 2026-04-06 21:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0024_cosignataire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inscriptions', '0011_eleve_created_by_eleve_updated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementParcours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('type_evenement', models.CharField(choices=[('PASSAGE', 'Passage en classe supérieure'), ('REDOUBLEMENT', 'Redoublement'), ('TRANSFERT_ENTRANT', 'Transfert entrant'), ('TRANSFERT_SORTANT', 'Transfert sortant'), ('ABANDON', 'Abandon scolaire'), ('DIPLOME', 'Diplôme obtenu'), ('AUTRE', 'Autre')], max_length=20, verbose_name="Type d'événement")),
                ('date_evenement', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('motif', models.TextField(blank=True, default='', help_text='Raison du redoublement, nom du diplôme, établissement de destination…', verbose_name='Motif / Observations')),
                ('etablissement_transfert', models.CharField(blank=True, default='', help_text="Établissement d'origine ou de destination pour les transferts", max_length=250, verbose_name='Établissement (transfert)')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements_parcours', to='parametres.anneescolaire', verbose_name='Année scolaire concernée')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements_parcours', to='inscriptions.eleve', verbose_name='Élève')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_parcours_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('inscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements', to='inscriptions.inscription', verbose_name='Inscription liée')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Événement de parcours',
                'verbose_name_plural': 'Événements de parcours',
                'ordering': ['annee_scolaire__date_debut', 'date_evenement'],
            },
        ),
    ]
