# Generated by Django 4.2.29 on 2026-04-11 16:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inscriptions', '0012_evenement_parcours'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransfertEleve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('etablissement_destination', models.CharField(max_length=250, verbose_name='Établissement de destination')),
                ('motif', models.TextField(blank=True, default='', verbose_name='Motif du transfert')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_demande', models.DateField(default=datetime.date.today, verbose_name='Date de la demande')),
                ('date_traitement', models.DateField(blank=True, null=True, verbose_name='Date de traitement')),
                ('notes_admin', models.TextField(blank=True, default='', verbose_name='Notes administratives')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('demandeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_demandes', to=settings.AUTH_USER_MODEL, verbose_name='Demandé par')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts', to='inscriptions.inscription', verbose_name='Inscription concernée')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_traites', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Transfert inter-établissements',
                'verbose_name_plural': 'Transferts inter-établissements',
                'ordering': ['-date_demande'],
            },
        ),
    ]
