# Generated by Django 4.2.29 on 2026-09-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0013_transfert_eleve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='matricule',
            field=models.CharField(help_text='Format: {CODE_ETAB}-{ANNEE}-{SEQ}', max_length=20, unique=True, verbose_name='Matricule'),
        ),
    ]
