# Generated by Django 4.2.29 on 2026-03-10 22:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('nom', models.CharField(max_length=255, verbose_name="Nom de l'établissement")),
                ('code', models.CharField(help_text="Code unique d'identification, ex: YSK", max_length=50, unique=True, verbose_name="Code de l'établissement")),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse géographique')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone principal')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Adresse email')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='etablissements/logos/', verbose_name="Logo de l'établissement")),
                ('cycles', models.CharField(blank=True, default='', help_text='Cycles séparés par des virgules : PRIMAIRE,SECONDAIRE', max_length=200, verbose_name='Cycles proposés')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(default='Burkina Faso', max_length=100, verbose_name='Pays')),
            ],
            options={
                'verbose_name': 'Établissement',
                'verbose_name_plural': 'Établissements',
                'ordering': ['nom'],
            },
        ),
    ]
