# Generated by Django 4.2.29 on 2026-04-03 12:21

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etablissements', '0002_etablissement_cycles_arrayfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='cycles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PRESCOLAIRE', 'Préscolaire'), ('PRIMAIRE', 'Primaire'), ('POST_PRIMAIRE', 'Post-primaire'), ('SECONDAIRE', 'Secondaire')], max_length=20), blank=True, default=list, size=None, verbose_name='Cycles proposés'),
        ),
    ]
