# Generated by Django 4.2.29 on 2026-04-11 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etablissements', '0003_etablissement_created_by_etablissement_updated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeEtablissements',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du groupe')),
                ('code', models.CharField(help_text='Code unique, ex: YELEN-GRP', max_length=50, unique=True, verbose_name='Code du groupe')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': "Groupe d'établissements",
                'verbose_name_plural': "Groupes d'établissements",
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='etablissement',
            name='groupe',
            field=models.ForeignKey(blank=True, help_text="Groupe d'établissements auquel appartient cet établissement (Licence RESEAU)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etablissements', to='etablissements.groupeetablissements', verbose_name='Groupe / Réseau'),
        ),
    ]
