# Generated by Django 4.2.29 on 2026-03-11 14:58

from django.db import migrations

def load_typedocument_data(apps, schema_editor):
    TypeDocument = apps.get_model('parametres', 'TypeDocument')
    
    docs = [
        TypeDocument(code='CERT_SCOL', libelle='Certificat de Scolarité', description='Document certifiant la scolarité de l\'élève'),
        TypeDocument(code='BULLETIN', libelle='Bulletin de Notes', description='Bulletin de notes périodique'),
        TypeDocument(code='RECU_PAIEMENT', libelle='Reçu de Paiement', description='Reçu pour un paiement effectué'),
        TypeDocument(code='AUTORISATION', libelle='Autorisation d\'Absence', description='Autorisation justifiant une absence'),
        TypeDocument(code='ATTESTATION', libelle='Attestation de Non-Redevabilité', description='Attestation prouvant que la scolarité est soldée'),
        TypeDocument(code='CURSUS', libelle='Cursus Scolaire Complet', description='Relevé des années précédentes de l\'élève'),
        TypeDocument(code='CARTE_ID', libelle='Carte d\'Identité Scolaire', description='Carte d\'identité interne à l\'école'),
        TypeDocument(code='LISTE_CLASSE', libelle='Liste Alphabétique de Classe', description='Liste nominative d\'une classe'),
        TypeDocument(code='LISTE_PERSONNEL', libelle='Liste du Personnel', description='Liste des employés de l\'établissement')
    ]
    
    TypeDocument.objects.bulk_create(docs, ignore_conflicts=True)

def unload_typedocument_data(apps, schema_editor):
    TypeDocument = apps.get_model('parametres', 'TypeDocument')
    TypeDocument.objects.filter(code__in=[
        'CERT_SCOL', 'BULLETIN', 'RECU_PAIEMENT', 'AUTORISATION', 
        'ATTESTATION', 'CURSUS', 'CARTE_ID', 'LISTE_CLASSE', 'LISTE_PERSONNEL'
    ]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_typedocument_data, reverse_code=unload_typedocument_data),
    ]
