# Generated by Django 4.2.29 on 2026-03-13 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0002_typedocument_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubriquepaiement',
            name='montant',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Montant par défaut en Francs CFA', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant (FCFA)'),
        ),
    ]
