# Generated by Django 4.2.29 on 2026-03-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0003_add_montant_to_rubrique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubriquepaiement',
            name='nom',
            field=models.CharField(help_text='Ex: Scolarité, Inscription, Cantine, etc.', max_length=200, verbose_name='Nom de la rubrique'),
        ),
    ]
