# Generated by Django 4.2.29 on 2026-03-13 13:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0001_initial'),
        ('parametres', '0004_increase_nom_rubrique_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='coefficient',
        ),
        migrations.CreateModel(
            name='CategorieDiscipline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('nom', models.CharField(help_text='Ex: Langues, Sciences, Sciences Humaines, etc.', max_length=100, verbose_name='Nom de la catégorie')),
                ('code', models.CharField(help_text='Code court unique, ex: LNG, SCI, SH', max_length=20, verbose_name='Code')),
                ('couleur', models.CharField(default='#6366F1', help_text='Code couleur pour affichage', max_length=7, verbose_name='Couleur')),
                ('ordre', models.IntegerField(default=1, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Catégorie active')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie_disciplines', to='etablissements.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Catégorie de discipline',
                'verbose_name_plural': 'Catégories de disciplines',
                'ordering': ['etablissement', 'ordre', 'nom'],
                'unique_together': {('etablissement', 'code')},
            },
        ),
        migrations.AddField(
            model_name='discipline',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplines', to='parametres.categoriediscipline', verbose_name='Catégorie'),
        ),
    ]
