# Generated by Django 4.2.29 on 2026-03-13 14:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0001_initial'),
        ('parametres', '0005_remove_discipline_coefficient_categoriediscipline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppreciationMoyenneSecondaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('libelle', models.CharField(help_text='Ex: Excellent, Bien, Passable, etc.', max_length=50, verbose_name='Libellé')),
                ('moy_min', models.DecimalField(decimal_places=2, default=0, help_text='Moyenne minimale pour cette appréciation sur 20', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Moyenne minimale')),
                ('moy_max', models.DecimalField(decimal_places=2, default=20, help_text='Moyenne maximale pour cette appréciation sur 20', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Moyenne maximale')),
                ('couleur', models.CharField(default='#00A86B', help_text='Code couleur hexadécimal', max_length=7, verbose_name='Couleur')),
                ('ordre', models.IntegerField(default=1, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Appréciation active')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreciations_conduite', to='etablissements.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Appréciation Moyenne Secondaire',
                'verbose_name_plural': 'Appréciations Moyenne Secondaire',
                'ordering': ['-moy_min'],
            },
        ),
        migrations.DeleteModel(
            name='AppreciationConduite',
        ),
    ]
