# Generated by Django 4.2.29 on 2026-03-13 15:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0007_appreciationmoyenneprimaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeSanction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('code', models.CharField(help_text='Ex: AVERTISSEMENT, BLAME, EXCLUSION_TEMP', max_length=20, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(help_text='Ex: Avertissement, Blâme, Exclusion temporaire', max_length=100, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Type actif')),
            ],
            options={
                'verbose_name': 'Type de Sanction',
                'verbose_name_plural': 'Types de Sanctions',
                'ordering': ['libelle'],
            },
        ),
    ]
