# Generated by Django 4.2.29 on 2026-03-15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0008_typesanction'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifscolarite',
            name='cycle',
            field=models.ForeignKey(
                blank=True,
                help_text='Laisser vide pour appliquer à tous les cycles',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tarifs',
                to='parametres.cycle',
                verbose_name='Cycle'
            ),
        ),
    ]
