# Generated by Django 4.2.29 on 2026-03-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0009_add_cycle_to_tarif'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedocument',
            name='categorie',
            field=models.CharField(choices=[('SCOLARITE', 'Scolarité'), ('FINANCE', 'Finance'), ('ADMINISTRATIF', 'Administratif'), ('PEDAGOGIE', 'Pédagogie'), ('PERSONNEL', 'Personnel')], default='SCOLARITE', max_length=20, verbose_name='Catégorie'),
        ),
    ]
