# Generated by Django 4.2.29 on 2026-03-17

from django.db import migrations


def set_categorie_for_existing_documents(apps, schema_editor):
    TypeDocument = apps.get_model('parametres', 'TypeDocument')
    
    categories_mapping = {
        'CERT_SCOL': 'SCOLARITE',
        'BULLETIN': 'SCOLARITE',
        'CURSUS': 'SCOLARITE',
        'CARTE_ID': 'SCOLARITE',
        'RECU_PAIEMENT': 'FINANCE',
        'ATTESTATION': 'FINANCE',
        'AUTORISATION': 'ADMINISTRATIF',
        'LISTE_CLASSE': 'PEDAGOGIE',
        'LISTE_PERSONNEL': 'PERSONNEL',
    }
    
    for code, categorie in categories_mapping.items():
        TypeDocument.objects.filter(code=code).update(categorie=categorie)


def reset_categorie_to_default(apps, schema_editor):
    TypeDocument = apps.get_model('parametres', 'TypeDocument')
    TypeDocument.objects.all().update(categorie='SCOLARITE')


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0010_typedocument_categorie'),
    ]

    operations = [
        migrations.RunPython(set_categorie_for_existing_documents, reset_categorie_to_default),
    ]
