# Generated by Django 4.2.29 on 2026-03-17 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0011_update_typedocument_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedocument',
            name='cycle',
            field=models.ForeignKey(blank=True, help_text='Laisser vide pour applies à tous les cycles', null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametres.cycle', verbose_name='Cycle'),
        ),
    ]
