# Generated by Django 4.2.29 on 2026-03-20 00:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0013_titreFonction_titrehonorifiquePersonnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='titrefonction',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='titrehonorifiquepersonnel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='titrefonction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='titrefonction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant'),
        ),
        migrations.AlterField(
            model_name='titrefonction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='titrehonorifiquepersonnel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='titrehonorifiquepersonnel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant'),
        ),
        migrations.AlterField(
            model_name='titrehonorifiquepersonnel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
    ]
