# Generated by Django 4.2.29 on 2026-03-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0017_signataire_fonction_titres_honorifiques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signatairedocument',
            name='fonction',
            field=models.CharField(blank=True, default='Le Directeur', help_text="Fonction affichée entre la date et le nom, ex: 'Directeur des Études', 'Le Proviseur', 'La Directrice'", max_length=150, verbose_name='Fonction'),
        ),
        migrations.AlterField(
            model_name='signatairedocument',
            name='titre',
            field=models.CharField(blank=True, default='', help_text="Champ hérité — utiliser 'fonction' à la place", max_length=100, verbose_name='Titre / Fonction (ancien)'),
        ),
        migrations.AlterField(
            model_name='signatairedocument',
            name='titre_honorifique',
            field=models.CharField(blank=True, default='', help_text="Champ hérité — utiliser 'titres_honorifiques' à la place", max_length=50, verbose_name='Titre Honorifique (ancien)'),
        ),
        migrations.AlterField(
            model_name='signatairedocument',
            name='titres_honorifiques',
            field=models.JSONField(blank=True, default=list, help_text='Liste ordonnée de titres honorifiques affichés sous le nom, ex: ["Chevalier de l\'Ordre du Mérite", "Chevalier des Palmes Académiques"]', verbose_name='Titres Honorifiques'),
        ),
    ]
