# Generated by Django 4.2.29 on 2026-04-04 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etablissements', '0003_etablissement_created_by_etablissement_updated_by_and_more'),
        ('parametres', '0020_anneescolaire_created_by_anneescolaire_updated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementCalendrier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('titre', models.CharField(max_length=150, verbose_name='Titre')),
                ('type', models.CharField(choices=[('CONGE', 'Congé scolaire'), ('JOUR_FERIE', 'Jour férié'), ('EXAMEN', 'Examen / Évaluation'), ('REUNION', 'Réunion pédagogique'), ('FERMETURE', 'Fermeture exceptionnelle'), ('AUTRE', 'Autre événement')], default='AUTRE', max_length=20, verbose_name='Type')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('journee_complete', models.BooleanField(default=True, verbose_name='Journée complète')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='parametres.anneescolaire', verbose_name='Année scolaire')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements_calendrier', to='etablissements.etablissement', verbose_name='Établissement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Événement calendrier',
                'verbose_name_plural': 'Événements calendrier',
                'ordering': ['date_debut'],
                'indexes': [models.Index(fields=['etablissement', 'annee_scolaire', 'date_debut'], name='parametres__etablis_a09778_idx')],
            },
        ),
    ]
