# Generated by Django 4.2.29 on 2026-04-04 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0003_etablissement_created_by_etablissement_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametres', '0021_add_evenement_calendrier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('type', models.CharField(choices=[('BULLETIN', 'Disponibilité du bulletin'), ('ABSENCE', 'Absence élève'), ('RETARD', 'Retard élève'), ('PAIEMENT', 'Relance paiement'), ('REUNION', "Réunion parents d'élèves")], max_length=20, verbose_name='Type de message')),
                ('contenu_sms', models.TextField(help_text='Max 160 caractères pour un SMS simple. Variables : {nom_eleve}, {classe}, etc.', verbose_name='Contenu SMS')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeles_messages', to='etablissements.etablissement', verbose_name='Établissement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Modèle de message',
                'verbose_name_plural': 'Modèles de messages',
                'ordering': ['type'],
                'unique_together': {('etablissement', 'type')},
            },
        ),
    ]
