# Generated by Django 4.2.29 on 2026-04-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0022_add_modele_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='typesanction',
            name='points_defaut',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Valeur pré-remplie lors de la création d'une sanction (négatif = pénalité).", max_digits=5, verbose_name='Points par défaut'),
        ),
    ]
