# Generated by Django 4.2.29 on 2026-04-06 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametres', '0023_typesanction_points_defaut'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoSignataire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('membre_personnel_id', models.UUIDField(blank=True, null=True, verbose_name='ID Membre du Personnel')),
                ('fonction', models.CharField(blank=True, default='', help_text="Ex : 'Le Censeur', 'La Directrice des Études'", max_length=150, verbose_name='Fonction')),
                ('titres_honorifiques', models.JSONField(blank=True, default=list, verbose_name='Titres honorifiques')),
                ('ordre', models.PositiveSmallIntegerField(default=2, help_text='1 = premier à gauche ; le signataire principal est toujours en position 1', verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('signataire_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_signataires', to='parametres.signatairedocument', verbose_name='Signataire principal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Co-Signataire',
                'verbose_name_plural': 'Co-Signataires',
                'ordering': ['ordre'],
            },
        ),
    ]
