# Generated by Django 4.2.29 on 2026-04-11 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0003_etablissement_created_by_etablissement_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametres', '0024_cosignataire'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclencheurSMS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('type_declencheur', models.CharField(choices=[('ABSENCE_J1', 'Absences non justifiées (J+1)'), ('ECHEANCIER', "Rappel d'échéancier"), ('RESULTATS', 'Bulletin disponible')], max_length=20, verbose_name='Type de déclencheur')),
                ('actif', models.BooleanField(default=False, verbose_name='Actif')),
                ('jours_avant', models.PositiveSmallIntegerField(default=3, help_text='Utilisé pour le type Échéancier : envoyer le rappel N jours avant la date limite.', verbose_name="Jours avant l'échéance")),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Dernière exécution')),
                ('nb_envoyes_total', models.PositiveIntegerField(default=0, verbose_name='SMS envoyés au total')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declencheurs_sms', to='etablissements.etablissement', verbose_name='Établissement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Déclencheur SMS automatique',
                'verbose_name_plural': 'Déclencheurs SMS automatiques',
                'ordering': ['type_declencheur'],
                'unique_together': {('etablissement', 'type_declencheur')},
            },
        ),
    ]
