# Generated by Django 4.2.29 on 2026-03-12 00:41

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametres', '0002_typedocument_data'),
        ('personnel', '0001_initial'),
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('coefficient', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Coefficient')),
                ('heures_hebdomadaires', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Heures hebdomadaires')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Enseignement actif')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to='parametres.anneescolaire', verbose_name='Année scolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to='parametres.classe', verbose_name='Classe')),
            ],
            options={
                'verbose_name': 'Enseignement',
                'verbose_name_plural': 'Enseignements',
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code matière')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la matière')),
                ('nom_complet', models.CharField(blank=True, default='', max_length=200, verbose_name='Nom complet')),
                ('categorie', models.CharField(choices=[('LANGUE', 'Langue'), ('SCIENTIFIQUE', 'Scientifique'), ('SOCIAL', 'Sciences Humaines et Sociales'), ('ART', 'Arts et Sports'), ('TECHNIQUE', 'Technique'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Catégorie')),
                ('coefficient', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3, verbose_name='Coefficient')),
                ('note_min', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Note minimale')),
                ('note_max', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Note maximale')),
                ('heures_hebdomadaires', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Heures hebdomadaires')),
                ('est_discipline', models.BooleanField(default=False, verbose_name='Matière de discipline')),
                ('est_obligatoire', models.BooleanField(default=True, verbose_name='Matière obligatoire')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TypeEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('coefficient', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3, verbose_name='Coefficient')),
                ('ponderation', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='Pondération')),
                ('nb_meilleures_notes', models.IntegerField(default=0, verbose_name='Nombre de meilleures notes conservées')),
                ('est_visible', models.BooleanField(default=True, verbose_name='Visible dans le bulletin')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': "Type d'évaluation",
                'verbose_name_plural': "Types d'évaluations",
                'ordering': ['ordre', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('type_periode', models.CharField(choices=[('TRIMESTRE', 'Trimestre'), ('SEMESTRE', 'Semestre')], default='TRIMESTRE', max_length=20, verbose_name='Type de période')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('numero', models.IntegerField(default=1, verbose_name='Numéro')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('notes_saisies', models.BooleanField(default=False, verbose_name='Saisie des notes terminée')),
                ('date_fermeture', models.DateField(blank=True, null=True, verbose_name='Date de fermeture')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trimestres', to='parametres.anneescolaire', verbose_name='Année scolaire')),
            ],
            options={
                'verbose_name': 'Trimestre',
                'verbose_name_plural': 'Trimestres',
                'ordering': ['annee_scolaire', 'numero'],
                'unique_together': {('annee_scolaire', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('moyenne', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Moyenne')),
                ('moyenne_sur_20', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Moyenne sur 20')),
                ('rang', models.IntegerField(blank=True, null=True, verbose_name='Rang')),
                ('nb_notes', models.IntegerField(default=0, verbose_name='Nombre de notes')),
                ('meilleure_note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Meilleure note')),
                ('pire_note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Pire note')),
                ('appreciation', models.TextField(blank=True, default='', verbose_name='Appréciation')),
                ('coefficient_utilise', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Coefficient utilisé')),
                ('enseignement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='pedagogie.enseignement', verbose_name='Enseignement')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='inscriptions.inscription', verbose_name='Inscription')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='pedagogie.trimestre', verbose_name='Trimestre')),
            ],
            options={
                'verbose_name': 'Résultat',
                'verbose_name_plural': 'Résultats',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('date_planifiee', models.DateField(verbose_name='Date prévue')),
                ('date_effectuee', models.DateField(blank=True, null=True, verbose_name='Date effective')),
                ('bareme', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Barème')),
                ('duree_minutes', models.IntegerField(default=60, verbose_name='Durée (minutes)')),
                ('coefficient', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Coefficient')),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PLANIFIEE', max_length=20, verbose_name='Statut')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observations')),
                ('enseignement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='pedagogie.enseignement', verbose_name='Enseignement')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='pedagogie.trimestre', verbose_name='Trimestre')),
                ('type_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='pedagogie.typeevaluation', verbose_name="Type d'évaluation")),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['-date_planifiee'],
            },
        ),
        migrations.AddField(
            model_name='enseignement',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to='pedagogie.matiere', verbose_name='Matière'),
        ),
        migrations.AddField(
            model_name='enseignement',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enseignements', to='personnel.membrepersonnel', verbose_name='Enseignant'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Note')),
                ('observation', models.TextField(blank=True, default='', verbose_name='Observation')),
                ('statut', models.CharField(choices=[('ENREGISTREE', 'Enregistrée'), ('VALIDEE', 'Validée'), ('MODIFIEE', 'Modifiée'), ('ANNULEE', 'Annulée')], default='ENREGISTREE', max_length=20, verbose_name='Statut')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='pedagogie.evaluation', verbose_name='Évaluation')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='inscriptions.inscription', verbose_name='Inscription')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_validees', to='personnel.membrepersonnel', verbose_name='Validée par')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'unique_together': {('inscription', 'evaluation')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='enseignement',
            unique_together={('matiere', 'classe', 'annee_scolaire')},
        ),
    ]
