# Generated by Django 4.2.29 on 2026-03-12 13:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0001_initial'),
        ('pedagogie', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resultat',
            unique_together={('inscription', 'enseignement', 'trimestre')},
        ),
        migrations.CreateModel(
            name='MoyenneGenerale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('moyenne', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Moyenne')),
                ('moyenne_sur_20', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Moyenne sur 20')),
                ('rang', models.IntegerField(blank=True, null=True, verbose_name='Rang')),
                ('total_points', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Total des points')),
                ('total_coefficients', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Total des coefficients')),
                ('nb_matieres_validees', models.IntegerField(default=0, verbose_name='Nombre de matières validées')),
                ('nb_matieres_total', models.IntegerField(default=0, verbose_name='Total des matières')),
                ('appreciation', models.TextField(blank=True, default='', verbose_name='Appréciation')),
                ('observation_generale', models.TextField(blank=True, default='', verbose_name='Observation générale')),
                ('est_valide', models.BooleanField(default=False, verbose_name='Moyenne validée')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes_generales', to='inscriptions.inscription', verbose_name='Inscription')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes_generales', to='pedagogie.trimestre', verbose_name='Trimestre')),
            ],
            options={
                'verbose_name': 'Moyenne générale',
                'verbose_name_plural': 'Moyennes générales',
                'ordering': ['trimestre', '-moyenne'],
                'unique_together': {('inscription', 'trimestre')},
            },
        ),
    ]
