# Generated by Django 4.2.29 on 2026-03-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogie', '0002_alter_resultat_unique_together_moyennegenerale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='note_max',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='note_min',
        ),
        migrations.AddField(
            model_name='matiere',
            name='moy_max',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Moyenne maximale'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='moy_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Moyenne minimale'),
        ),
    ]
