# Generated by Django 4.2.29 on 2026-03-21 23:09

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogie', '0004_matierecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='matierecycle',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='coefficient',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3, verbose_name='Coefficient par défaut'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='moy_max',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Barème maximal par défaut'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='moy_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Barème minimal par défaut'),
        ),
        migrations.AlterField(
            model_name='matierecycle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='matierecycle',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant'),
        ),
        migrations.AlterField(
            model_name='matierecycle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
    ]
