# Generated by Django 4.2.29 on 2026-03-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogie', '0005_matierecycle_is_active_alter_matiere_coefficient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultat',
            name='dispense',
            field=models.BooleanField(default=False, verbose_name='Dispensé'),
        ),
    ]
