# Generated by Django 4.2.29 on 2026-04-07 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0012_evenement_parcours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedagogie', '0007_enseignement_created_by_enseignement_updated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RisqueDecrochage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='Score de risque (0–100)')),
                ('niveau', models.CharField(choices=[('FAIBLE', 'Faible'), ('MODERE', 'Modéré'), ('ELEVE', 'Élevé'), ('CRITIQUE', 'Critique')], default='FAIBLE', max_length=10, verbose_name='Niveau de risque')),
                ('facteurs', models.JSONField(default=list, help_text='Liste de dicts {libelle, points, detail}', verbose_name='Facteurs contributeurs')),
                ('date_calcul', models.DateTimeField(auto_now=True, verbose_name='Date du dernier calcul')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risque_decrochage', to='inscriptions.inscription', verbose_name='Inscription')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Risque de décrochage',
                'verbose_name_plural': 'Risques de décrochage',
                'ordering': ['-score'],
            },
        ),
    ]
