# Generated by Django 4.2.29 on 2026-05-03 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedagogie', '0008_risquedecrochage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CahierTextes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('date', models.DateField(verbose_name='Date du cours')),
                ('heure_debut', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('contenu', models.TextField(verbose_name='Contenu du cours')),
                ('devoirs', models.TextField(blank=True, default='', verbose_name='Devoirs donnés')),
                ('date_remise_devoirs', models.DateField(blank=True, null=True, verbose_name='Date de remise des devoirs')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('enseignement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrees_cahier', to='pedagogie.enseignement', verbose_name='Enseignement')),
                ('redige_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrees_cahier', to=settings.AUTH_USER_MODEL, verbose_name='Rédigé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Entrée du cahier de textes',
                'verbose_name_plural': 'Cahier de textes',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
