# Generated by Django 4.2.29 on 2026-05-04 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametres', '0025_declencheur_sms'),
        ('inscriptions', '0013_transfert_eleve'),
        ('pedagogie', '0010_prediction_reussite_examen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('libelle', models.CharField(max_length=300, verbose_name='Libellé de la compétence')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description / indicateurs')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='parametres.cycle', verbose_name='Cycle')),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competences', to='pedagogie.matiere', verbose_name='Matière')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['cycle', 'matiere__code', 'ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationCompetence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('niveau', models.CharField(choices=[('ACQUIS', 'Acquis'), ('EN_COURS', "En cours d'acquisition"), ('NON_ACQUIS', 'Non acquis'), ('NON_EVALUE', 'Non évalué')], default='NON_EVALUE', max_length=12, verbose_name="Niveau d'acquisition")),
                ('observation', models.CharField(blank=True, default='', max_length=200, verbose_name='Observation')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='pedagogie.competence', verbose_name='Compétence')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_competences', to='inscriptions.inscription', verbose_name='Inscription')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_competences', to='pedagogie.trimestre', verbose_name='Trimestre')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Évaluation de compétence',
                'verbose_name_plural': 'Évaluations de compétences',
                'ordering': ['competence__ordre'],
                'unique_together': {('inscription', 'competence', 'trimestre')},
            },
        ),
    ]
