# Generated by Django 4.2.29 on 2026-06-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogie', '0011_competences'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competence',
            options={'ordering': ['cycle', 'matiere__code', 'categorie', 'ordre', 'libelle'], 'verbose_name': 'Compétence', 'verbose_name_plural': 'Compétences'},
        ),
        migrations.AddField(
            model_name='competence',
            name='categorie',
            field=models.CharField(choices=[('SAVOIRS_ACAD', 'Savoirs académiques'), ('COMP_PRATIQUE', 'Compétences pratiques de vie'), ('HYGIENE', 'Hygiène et santé collective'), ('ENVIRONNEMENT', 'Environnement et développement durable'), ('PATRIMOINE', 'Citoyenneté et patrimoine'), ('TRANSVERSALE', 'Compétence transversale')], default='SAVOIRS_ACAD', max_length=30, verbose_name='Catégorie APC'),
        ),
    ]
