# Generated by Django 5.2.17 on 2026-10-10 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0025_declencheur_sms'),
        ('pedagogie', '0012_ajout_categorie_competence_apc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matierecycle',
            options={'ordering': ['cycle__ordre', 'cycle__nom', 'niveau', 'serie'], 'verbose_name': 'Configuration matière/cycle', 'verbose_name_plural': 'Configurations matière/cycle'},
        ),
        migrations.AlterUniqueTogether(
            name='matierecycle',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='matierecycle',
            name='niveau',
            field=models.CharField(blank=True, default='', help_text='Vide = tout le cycle. Ex : CM2, 6ème, Tle', max_length=50, verbose_name='Niveau'),
        ),
        migrations.AddField(
            model_name='matierecycle',
            name='serie',
            field=models.CharField(blank=True, default='', help_text='Vide = toutes les séries du niveau', max_length=10, verbose_name='Série BAC'),
        ),
        migrations.AddConstraint(
            model_name='matierecycle',
            constraint=models.UniqueConstraint(fields=('matiere', 'cycle', 'niveau', 'serie'), name='pedagogie_matierecycle_portee_unique'),
        ),
    ]
