# Generated by Django 4.2.29 on 2026-03-12 13:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametres', '0002_typedocument_data'),
        ('pedagogie', '0002_alter_resultat_unique_together_moyennegenerale'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratVacation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('taux_horaire', models.DecimalField(decimal_places=0, default=Decimal('2500'), help_text='Montant payé par heure de cours effectuée', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taux horaire (FCFA)')),
                ('heures_hebdo_prevues', models.DecimalField(decimal_places=1, default=Decimal('2.0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))], verbose_name='Heures hebdomadaires prévues')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('actif', models.BooleanField(default=True, verbose_name='Contrat actif')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats_vacation', to='parametres.anneescolaire', verbose_name='Année scolaire')),
                ('enseignement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_vacation', to='pedagogie.enseignement', verbose_name='Enseignement (matière × classe)')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats_vacation', to='personnel.membrepersonnel', verbose_name='Vacataire')),
            ],
            options={
                'verbose_name': 'Contrat de Vacation',
                'verbose_name_plural': 'Contrats de Vacation',
                'ordering': ['-annee_scolaire', 'personnel__nom'],
                'unique_together': {('personnel', 'annee_scolaire', 'enseignement')},
            },
        ),
        migrations.CreateModel(
            name='HeureVacation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('mois', models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mois')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('heures_effectuees', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Heures effectuées')),
                ('heures_annulees', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Heures annulées / non remplacées')),
                ('est_valide', models.BooleanField(default=False, verbose_name='Heures validées')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observations')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heures', to='vacations.contratvacation', verbose_name='Contrat')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heures_vacation_validees', to='personnel.membrepersonnel', verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Heures de Vacation',
                'verbose_name_plural': 'Heures de Vacation',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('contrat', 'mois', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='BulletinVacation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('mois', models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mois')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('total_heures', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=6, verbose_name='Total heures payables')),
                ('montant_total', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Montant total (FCFA)')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('PAYE', 'Payé')], default='BROUILLON', max_length=10, verbose_name='Statut')),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('reference_paiement', models.CharField(blank=True, default='', max_length=100, verbose_name='Référence paiement')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins_vacation', to='parametres.anneescolaire', verbose_name='Année scolaire')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins_vacation', to='personnel.membrepersonnel', verbose_name='Vacataire')),
            ],
            options={
                'verbose_name': 'Bulletin de Vacation',
                'verbose_name_plural': 'Bulletins de Vacation',
                'ordering': ['-annee', '-mois', 'personnel__nom'],
                'unique_together': {('personnel', 'mois', 'annee')},
            },
        ),
    ]
