# Generated by Django 4.2.29 on 2026-03-12 13:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametres', '0002_typedocument_data'),
        ('personnel', '0001_initial'),
        ('pedagogie', '0002_alter_resultat_unique_together_moyennegenerale'),
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure_debut', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('est_clos', models.BooleanField(default=False, help_text='Une fois clôturé, les présences ne peuvent plus être modifiées', verbose_name='Appel clôturé')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observations')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels', to='parametres.anneescolaire', verbose_name='Année scolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels', to='parametres.classe', verbose_name='Classe')),
                ('effectue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appels_effectues', to='personnel.membrepersonnel', verbose_name='Effectué par')),
                ('enseignement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appels', to='pedagogie.enseignement', verbose_name='Enseignement (matière)')),
            ],
            options={
                'verbose_name': 'Appel',
                'verbose_name_plural': 'Appels',
                'ordering': ['-date', 'classe'],
                'unique_together': {('classe', 'date', 'enseignement')},
            },
        ),
        migrations.CreateModel(
            name='Justification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('motif', models.TextField(verbose_name='Motif')),
                ('document', models.FileField(blank=True, help_text='Certificat médical, courrier, etc.', null=True, upload_to='presences/justifications/', verbose_name='Document justificatif')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=15, verbose_name='Statut')),
                ('date_traitement', models.DateField(blank=True, null=True, verbose_name='Date de traitement')),
                ('observation_traitement', models.TextField(blank=True, default='', verbose_name='Observation du responsable')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justifications', to='inscriptions.inscription', verbose_name='Inscription élève')),
                ('traitee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justifications_traitees', to='personnel.membrepersonnel', verbose_name='Traitée par')),
            ],
            options={
                'verbose_name': 'Justification',
                'verbose_name_plural': 'Justifications',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('statut', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('RETARD', 'En retard'), ('EXCUSE', 'Excusé')], default='PRESENT', max_length=10, verbose_name='Statut')),
                ('minutes_retard', models.IntegerField(default=0, help_text='0 si non applicable', verbose_name='Minutes de retard')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observations')),
                ('appel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='presences.appel', verbose_name='Appel')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='inscriptions.inscription', verbose_name='Inscription élève')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['appel__date', 'inscription__eleve__nom'],
                'unique_together': {('appel', 'inscription')},
            },
        ),
    ]
