# Generated by Django 4.2.29 on 2026-03-10 15:53

import accounts.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etablissements', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('email', models.EmailField(help_text='Utilisé comme identifiant de connexion.', max_length=254, unique=True, verbose_name='Adresse email')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin Éditeur'), ('DIRECTEUR', 'Directeur / Proviseur'), ('CENSEUR', 'Censeur / Proviseur'), ('AVS', 'Agent de Vie Scolaire'), ('ENSEIGNANT', 'Enseignant'), ('COMPTABLE', 'Comptable'), ('SECRETAIRE', 'Secrétaire'), ('PARENT', 'Parent'), ('ELEVE', 'Élève')], default='ENSEIGNANT', help_text='Rôle RBAC déterminant les permissions.', max_length=20, verbose_name='Rôle')),
                ('telephone', models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone')),
                ('etablissement', models.ForeignKey(blank=True, help_text='Établissement de rattachement. Null pour Super Admin.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='etablissements.etablissement', verbose_name='Établissement')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
