# Generated by Django 4.2.29 on 2026-04-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0011_eleve_created_by_eleve_updated_by_and_more'),
        ('accounts', '0002_add_audit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eleves_lies',
            field=models.ManyToManyField(blank=True, help_text='Élèves associés à ce compte (enfants pour un parent, soi-même pour un élève).', related_name='utilisateurs_lies', to='inscriptions.eleve', verbose_name='Élèves liés'),
        ),
    ]
