# Generated by Django 4.2.29 on 2026-04-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_totp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Tentatives de connexion échouées'),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, help_text='Date de fin du verrouillage temporaire.', null=True, verbose_name="Compte verrouillé jusqu'à"),
        ),
    ]
