# Generated by Django 4.2.29 on 2026-04-11 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0004_groupe_etablissements'),
        ('accounts', '0005_user_failed_login_attempts_user_locked_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='groupe',
            field=models.ForeignKey(blank=True, help_text='Groupe géré (pour le rôle Directeur Réseau).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs_reseau', to='etablissements.groupeetablissements', verbose_name='Groupe / Réseau'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin Éditeur'), ('DIRECTEUR_RESEAU', 'Directeur Réseau'), ('DIRECTEUR', 'Directeur / Proviseur'), ('CENSEUR', 'Censeur / Proviseur'), ('AVS', 'Agent de Vie Scolaire'), ('ENSEIGNANT', 'Enseignant'), ('COMPTABLE', 'Comptable'), ('SECRETAIRE', 'Secrétaire'), ('PARENT', 'Parent'), ('ELEVE', 'Élève')], default='ENSEIGNANT', help_text='Rôle RBAC déterminant les permissions.', max_length=20, verbose_name='Rôle'),
        ),
    ]
