# Generated by Django 5.2.17 on 2026-09-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_groupe_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(
                default=False,
                help_text='Force le changement du mot de passe à la prochaine connexion.',
                verbose_name='Changement de mot de passe requis',
            ),
        ),
    ]
