"""
Django settings for yelen_school project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import sys
import warnings


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# Mode debug - désactiver en production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        import secrets
        SECRET_KEY = secrets.token_hex(64)
    else:
        import secrets
        SECRET_KEY = secrets.token_hex(64)
        warnings.warn(
            "SECRET_KEY non définie - génération automatique. "
            "En production, définissez la variable d'environnement SECRET_KEY."
        )



# Hôtes autorisés - définir en production via ALLOWED_HOSTS env var
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]
if not ALLOWED_HOSTS and DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']

# Ajout automatique de l'IP locale pour l'accès réseau local
import socket
try:
    _hostname = socket.gethostname()
    _lan_ip = socket.gethostbyname(_hostname)
    if _lan_ip and not _lan_ip.startswith('127.'):
        ALLOWED_HOSTS.append(_lan_ip)
        ALLOWED_HOSTS.append(_hostname)
except Exception:
    pass

# Déduplication et nettoyage
ALLOWED_HOSTS = list(dict.fromkeys(h for h in ALLOWED_HOSTS if h))

# ── SÉCURITÉ HTTP (Production) ────────────────────────────────────────────────
# SSL Redirect — désactiver pour déploiement local sans HTTPS (via DISABLE_HTTPS_REDIRECT=true)
_SECURE_SSL_REDIRECT = os.environ.get('DISABLE_HTTPS_REDIRECT', 'false').lower() != 'true'

if not DEBUG:
    # HSTS - Force HTTPS pendant 1 an
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # HTTPS obligatoire (désactivable via DISABLE_HTTPS_REDIRECT)
    if _SECURE_SSL_REDIRECT:
        SECURE_SSL_REDIRECT = True
    
    # Cookie sécurisé
    SESSION_COOKIE_SECURE = bool(_SECURE_SSL_REDIRECT)
    CSRF_COOKIE_SECURE = bool(_SECURE_SSL_REDIRECT)
    
    # Prévention XSS / sniffing
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # Referrer Policy
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

    # Content-Security-Policy : gérée par CSPNonceMiddleware (csp_middleware.py)
    # Les anciennes SECURE_CSP_* n'étaient pas lues par Django — supprimées.

# Autorise les requêtes POST/CSRF depuis les origines de confiance
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', 'https://localhost,https://127.0.0.1').split(',') if o.strip()]

# Ajout automatique de l'IP locale pour l'accès réseau local
try:
    _lan_ip = socket.gethostbyname(socket.gethostname())
    if _lan_ip and not _lan_ip.startswith('127.'):
        _lan_origin = f'http://{_lan_ip}:8000'
        if _lan_origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(_lan_origin)
except Exception:
    pass

# Indique à Django qu'il est derrière un proxy HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ── Contrôle des licences (anti-fraude) ───────────────────────────────────────
# true  = vérification des licences ACTIVE (middlewares de validité, limites
#         et contexte + feature flags des vues). Licence expirée ou révoquée
#         → accès bloqué, redirigé vers les pages licences.
# false = mode démonstration / développement — aucune restriction.
# Valeur par défaut SÛRE : activé sauf si explicitement désactivé, ou si
# DEBUG=true et variable absente (développement local). Un .env de production
# qui oublie la ligne reste donc protégé.
_lic_env = os.environ.get('LICENSE_ENFORCEMENT')
if _lic_env is None:
    # Sous pytest, mode démo par défaut (les tests licences activent le flag
    # explicitement via `settings.LICENSE_ENFORCEMENT = True`).
    LICENSE_ENFORCEMENT = not DEBUG and 'PYTEST_CURRENT_TEST' not in os.environ and 'pytest' not in sys.modules
else:
    LICENSE_ENFORCEMENT = _lic_env.lower() == 'true'
if not DEBUG and not LICENSE_ENFORCEMENT:
    warnings.warn(
        "LICENSE_ENFORCEMENT=false alors que DEBUG=False : le contrôle des licences "
        "est DÉSACTIVÉ (mode démo). En production, mettre LICENSE_ENFORCEMENT=true."
    )

# P1 — Architecture anti-fraude définitive
# Clé dédiée pour signer les licences (au lieu de SECRET_KEY Django) — faille structurelle du mode autonome
LICENCE_SIGNING_KEY = os.environ.get('LICENCE_SIGNING_KEY', '')  # HMAC legacy, ou vide = fallback SECRET_KEY
# Ed25519 : clé publique dans l'app (vérification), privée chez éditeur (signature)
# Format attendu : hex 32 bytes (64 chars hex) ou base64 44 chars
LICENCE_PUBLIC_KEY = os.environ.get('LICENCE_PUBLIC_KEY', '')
LICENCE_PRIVATE_KEY = os.environ.get('LICENCE_PRIVATE_KEY', '')  # seulement chez éditeur, jamais en prod école
# Phone-home : URL serveur éditeur pour heartbeat signé (optionnel)
LICENCE_HEARTBEAT_URL = os.environ.get('LICENCE_HEARTBEAT_URL', '')
LICENCE_HEARTBEAT_INTERVAL_HOURS = int(os.environ.get('LICENCE_HEARTBEAT_INTERVAL_HOURS', '24'))
# Bail hors-ligne : fenêtre décroissante si pas de heartbeat (jours)
LICENCE_OFFLINE_GRACE_DAYS = int(os.environ.get('LICENCE_OFFLINE_GRACE_DAYS', '7'))
LICENCE_OFFLINE_MAX_DAYS = int(os.environ.get('LICENCE_OFFLINE_MAX_DAYS', '30'))
# Binding machine : empreinte multi-attributs
LICENCE_BINDING_ENABLED = os.environ.get('LICENCE_BINDING_ENABLED', 'false').lower() == 'true'
# Anti-tamper : vérification intégrité modules licences au boot
LICENCE_ANTITAMPER_ENABLED = os.environ.get('LICENCE_ANTITAMPER_ENABLED', 'false').lower() == 'true'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Requis par plusieurs templates ({% load humanize %}) : dashboard réseau,
    # échéancier global, transferts inter-établissements…
    'django.contrib.humanize',
    # Apps YELEN SCHOOL
    'core',
    'personnel',
    'parametres',
    'accounts',
    'licences',
    'etablissements',
    'inscriptions',
    'pedagogie',
    'finances',
    'presences',
    'documents',
    'examens',
    'vacations',
    'viescolaire',
    'bulletins',
    'manuels',
    'communication',
    # API REST
    'rest_framework',
    'rest_framework.authtoken',
    'api',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.authentication.ExpiringTokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DATETIME_FORMAT': '%Y-%m-%dT%H:%M:%S',
    'DATE_FORMAT': '%Y-%m-%d',
    # Rate limiting - 100 requêtes/minute par utilisateur
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/min',
        'user': '100/min',
        'login': '5/min',  # Limite login pour éviter brute force
    },
}

# django.contrib.postgres n'a de sens (et ne se charge) qu'avec PostgreSQL
if os.environ.get('DB_ENGINE', 'postgresql').strip().lower() != 'sqlite':
    INSTALLED_APPS.insert(INSTALLED_APPS.index('django.contrib.staticfiles') + 1, 'django.contrib.postgres')

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # CSP nonces — doit être APRÈS AuthenticationMiddleware
    'yelen_school.csp_middleware.CSPNonceMiddleware',
    # Restriction rôles PARENT/ÉLÈVE — doit être APRÈS AuthenticationMiddleware
    'yelen_school.role_middleware.RoleAccessMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'yelen_school.audit_middleware.AuditRequestMiddleware',
    # Génération automatique de l'année scolaire (désactivé — création manuelle)
    # 'parametres.middleware.AnneeScolaireAutoMiddleware',
]

# Middlewares de contrôle des licences — actifs uniquement si
# LICENSE_ENFORCEMENT=true (voir ci-dessus). Ordre imposé : Check → Limits →
# Contexte. En mode développement/démo (LICENSE_ENFORCEMENT=false), le
# middleware n'est pas chargé : comportement identique à avant l'activation.
if LICENSE_ENFORCEMENT:
    MIDDLEWARE += [
        'licences.middleware.LicenceCheckMiddleware',
        'licences.middleware.LicenceLimitsMiddleware',
        'licences.middleware.LicenceContextMiddleware',
    ]

ROOT_URLCONF = 'yelen_school.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'yelen_school.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Deux modes de déploiement, sélectionnés par la variable d'environnement DB_ENGINE :
#   DB_ENGINE=postgresql (défaut) → mode serveur / Docker : PostgreSQL + Redis
#   DB_ENGINE=sqlite              → mode autonome : un seul fichier de base de
#                                   données (SQLITE_PATH), aucun service externe.
#                                   Les postes clients accèdent au serveur par le
#                                   navigateur ; seul le serveur ouvre le fichier.
DB_ENGINE = os.environ.get('DB_ENGINE', 'postgresql').strip().lower()
IS_SQLITE = DB_ENGINE == 'sqlite'

if IS_SQLITE:
    SQLITE_PATH = Path(os.environ.get('SQLITE_PATH', BASE_DIR / 'data' / 'yelen_school.sqlite3'))
    SQLITE_PATH.parent.mkdir(parents=True, exist_ok=True)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': SQLITE_PATH,
            'OPTIONS': {
                # Attente max (s) lorsqu'un autre worker écrit — évite "database is locked"
                'timeout': 30,
            },
            # Réutilisation des connexions entre requêtes (le fichier reste ouvert)
            'CONN_MAX_AGE': 600,
            'CONN_HEALTH_CHECKS': True,
        }
    }
    # Les PRAGMA (WAL, synchronous, busy_timeout…) sont appliqués à chaque
    # nouvelle connexion par core/db_sqlite.py (signal connection_created),
    # car Django 4.2 ne propose pas encore l'option `init_command` pour SQLite.
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'yelen_school_db'),
            'USER': os.environ.get('DB_USER', 'yelen_user'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'yelen_password_dev'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Ouagadougou'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Email — console par défaut (sûr en local), SMTP si EMAIL_HOST configuré
if os.environ.get('EMAIL_HOST'):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Authentification
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# ── SMS ────────────────────────────────────────────────────────────────────
# SMS_BACKEND = 'http'   → passerelle WiFi locale (app Android "SMS Gateway")
# SMS_BACKEND = 'serial' → modem GSM USB ou Bluetooth SPP (AT commands)
SMS_ENABLED = os.environ.get('SMS_ENABLED', 'False').lower() == 'true'
SMS_BACKEND = os.environ.get('SMS_BACKEND', 'http')  # 'http' | 'serial'

# Backend HTTP (recommandé — téléphone Android sur le même réseau WiFi)
# App : https://github.com/capcom6/android-sms-gateway
SMS_HTTP_URL = os.environ.get('SMS_HTTP_URL', 'http://192.168.1.100:8080/message')
SMS_HTTP_USER = os.environ.get('SMS_HTTP_USER', 'admin')
SMS_HTTP_PASSWORD = os.environ.get('SMS_HTTP_PASSWORD', '')
SMS_HTTP_TIMEOUT = int(os.environ.get('SMS_HTTP_TIMEOUT', '10'))

# Backend série (modem USB Huawei/ZTE ou Android Bluetooth SPP)
SMS_MODEM_PORT = os.environ.get('SMS_MODEM_PORT', 'COM3')  # ex: /dev/ttyUSB0
SMS_MODEM_BAUD = int(os.environ.get('SMS_MODEM_BAUD', '9600'))
SMS_MODEM_TIMEOUT = int(os.environ.get('SMS_MODEM_TIMEOUT', '10'))

# ── WEBHOOK SMS ────────────────────────────────────────────────────────────────
# Token partagé : l'application SMS Gateway doit inclure ?token=... dans l'URL
SMS_WEBHOOK_TOKEN = os.environ.get('SMS_WEBHOOK_TOKEN', '')
# IP autorisées à appeler le webhook (séparées par des virgules)
SMS_ALLOWED_IPS = [ip.strip() for ip in os.environ.get('SMS_ALLOWED_IPS', '').split(',') if ip.strip()]
# Secret HMAC pour signature des requêtes (A1) — si défini, vérifie X-SMS-Signature
SMS_WEBHOOK_SECRET = os.environ.get('SMS_WEBHOOK_SECRET', '')
# Rate limiting webhook : max requêtes par minute par IP
SMS_WEBHOOK_RATE_LIMIT = int(os.environ.get('SMS_WEBHOOK_RATE_LIMIT', '30'))

# ── SÉCURITÉ RENFORCÉE ─────────────────────────────────────────────────────────

# Politique de mot de passe renforcée (12 caractères minimum)
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 12},  # 12 caractères minimum
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Session - sécurité production
SESSION_COOKIE_SECURE = not DEBUG and _SECURE_SSL_REDIRECT
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = int(os.environ.get('SESSION_COOKIE_AGE', '3600'))  # 1 heure
SESSION_SAVE_EVERY_REQUEST = True

# CSRF
CSRF_COOKIE_SECURE = not DEBUG and _SECURE_SSL_REDIRECT
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'

# Expiration des tokens API — 24 h par défaut (ajustable via variable d'env)
TOKEN_EXPIRY_HOURS = int(os.environ.get('TOKEN_EXPIRY_HOURS', '24'))

# Limites upload — prévention DoS
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024   # 5 Mo en mémoire
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 Mo max par requête

# ── LOGGING ────────────────────────────────────────────────────────────────────
LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'django.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'security_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'security.log',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 3,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['security_file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# Cache — doit être PARTAGÉ entre les workers (Gunicorn/Waitress) : le code
# l'utilise comme état commun (année courante, statut licence, config SMS runtime).
#   CACHE_BACKEND=redis    (défaut en mode PostgreSQL) → Redis
#   CACHE_BACKEND=database (défaut en mode SQLite)     → table dans la base, aucun service
#   CACHE_BACKEND=file                                 → répertoire CACHE_DIR
#   CACHE_BACKEND=locmem                               → mémoire (mono-process uniquement)
CACHE_BACKEND = os.environ.get('CACHE_BACKEND', 'database' if IS_SQLITE else 'redis').strip().lower()

if CACHE_BACKEND == 'redis':
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': os.environ.get('REDIS_URL', 'redis://redis:6379/1'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            }
        }
    }
elif CACHE_BACKEND == 'file':
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
            'LOCATION': os.environ.get('CACHE_DIR', str(BASE_DIR / 'data' / 'cache')),
            'OPTIONS': {'MAX_ENTRIES': 5000},
        }
    }
elif CACHE_BACKEND == 'locmem':
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'yelen-school',
        }
    }
else:  # 'database' — table créée par `manage.py createcachetable` (automatique via start_autonome)
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
            'LOCATION': 'yelen_cache',
            'OPTIONS': {'MAX_ENTRIES': 5000, 'CULL_FREQUENCY': 4},
        }
    }
