# Generated by Django 4.2.29 on 2026-03-12 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametres', '0002_typedocument_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='documents/pdf/%Y/%m/', verbose_name='Fichier PDF')),
                ('signataire_nom', models.CharField(blank=True, default='', help_text='Nom du signataire au moment de la génération', max_length=200, verbose_name='Nom du signataire (snapshot)')),
                ('numero_document', models.CharField(blank=True, default='', help_text='Numéro de série unique, ex: CERT-2026-00001', max_length=50, verbose_name='Numéro du document')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observations')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='parametres.anneescolaire', verbose_name='Année scolaire')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='parametres.classe', verbose_name='Classe (document collectif)')),
                ('genere_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_generes', to=settings.AUTH_USER_MODEL, verbose_name='Généré par')),
                ('inscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='inscriptions.inscription', verbose_name='Inscription (élève)')),
                ('type_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='parametres.typedocument', verbose_name='Type de document')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
