# Generated by Django 4.2.29 on 2026-04-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_created_by_document_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.PositiveSmallIntegerField(default=1, help_text='Numéro de version — incrémenté à chaque regénération du même document', verbose_name='Version'),
        ),
    ]
