# Generated by Django 4.2.29 on 2026-03-11 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etablissements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('cle_licence', models.CharField(editable=False, help_text='Clé unique générée automatiquement', max_length=19, unique=True, verbose_name='Clé de licence')),
                ('type_licence', models.CharField(choices=[('STARTER', '🥉 Starter - Licence Découverte'), ('STANDARD', '🥈 Standard - Licence Essentielle'), ('PREMIUM', '🥇 Premium - Licence Intégrale'), ('RESEAU', '🏆 Réseau - Licence Groupe')], default='STARTER', max_length=10, verbose_name='Type de licence')),
                ('statut', models.CharField(choices=[('ACTIVE', '✅ Active'), ('EXPIREE', '⏰ Expirée'), ('REVOQUEE', '🚫 Révoquée'), ('EN_ATTENTE', "⏳ En attente d'activation")], default='EN_ATTENTE', max_length=15, verbose_name='Statut')),
                ('date_activation', models.DateTimeField(blank=True, help_text='Date de première activation de la licence', null=True, verbose_name="Date d'activation")),
                ('date_expiration', models.DateField(help_text='Date de fin de validité de la licence', verbose_name="Date d'expiration")),
                ('signature_hmac', models.CharField(editable=False, help_text='Signature cryptographique pour empêcher la falsification', max_length=64, verbose_name='Signature HMAC')),
                ('notes_interne', models.TextField(blank=True, default='', help_text="Remarques internes (non visibles par l'établissement)", verbose_name='Notes internes')),
                ('derniere_verification', models.DateTimeField(blank=True, help_text='Date de la dernière vérification de validité', null=True, verbose_name='Dernière vérification')),
                ('etablissement', models.OneToOneField(help_text='Établissement associé à cette licence', on_delete=django.db.models.deletion.PROTECT, related_name='licence', to='etablissements.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Licence',
                'verbose_name_plural': 'Licences',
                'ordering': ['-date_activation'],
            },
        ),
        migrations.CreateModel(
            name='LicenceAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('action', models.CharField(choices=[('CREATION', '🆕 Création de licence'), ('ACTIVATION', '✅ Activation'), ('RENOUVELLEMENT', '🔄 Renouvellement'), ('REVOCATION', '🚫 Révocation'), ('MODIFICATION', '✏️ Modification'), ('VERIFICATION', '🔍 Vérification de validité'), ('EXPIRATION', '⏰ Expiration'), ('TENTATIVE_FRAUDE', '⚠️ Tentative de fraude détectée')], max_length=50, verbose_name='Action')),
                ('description', models.TextField(help_text="Détails de l'action effectuée", verbose_name='Description')),
                ('acteur_systeme', models.BooleanField(default=False, help_text="True si l'action a été effectuée automatiquement", verbose_name='Action système')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='User Agent')),
                ('hash_precedent', models.CharField(blank=True, default='', help_text="Lien vers l'entrée précédente pour détecter les modifications", max_length=64, verbose_name="Hash de l'entrée précédente")),
                ('hash_actuel', models.CharField(editable=False, max_length=64, verbose_name='Hash de cette entrée')),
                ('acteur_user', models.ForeignKey(blank=True, help_text="Utilisateur ayant effectué l'action (null si système)", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('licence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='licences.licence', verbose_name='Licence')),
            ],
            options={
                'verbose_name': "Entrée d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-created_at'],
                'permissions': [('view_audit_log', "Peut consulter le journal d'audit")],
                'indexes': [models.Index(fields=['licence', '-created_at'], name='licences_li_licence_c31c99_idx'), models.Index(fields=['action', '-created_at'], name='licences_li_action_932e43_idx')],
            },
        ),
        migrations.CreateModel(
            name='LicenceAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('type_alerte', models.CharField(choices=[('J-30', '⚠️ Expiration dans 30 jours'), ('J-15', '⚠️ Expiration dans 15 jours'), ('J-7', '🚨 Expiration dans 7 jours'), ('J-1', '🚨 Expiration DEMAIN'), ('EXPIREE', '🔴 Licence expirée')], max_length=10, verbose_name="Type d'alerte")),
                ('date_alerte', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de l'alerte")),
                ('envoyee', models.BooleanField(default=False, help_text="True si l'email de notification a été envoyé", verbose_name='Alerte envoyée')),
                ('date_envoi', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi de l'email")),
                ('destinataires', models.JSONField(default=list, help_text="Liste des emails ayant reçu l'alerte", verbose_name='Destinataires')),
                ('licence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='licences.licence', verbose_name='Licence')),
            ],
            options={
                'verbose_name': 'Alerte de licence',
                'verbose_name_plural': 'Alertes de licence',
                'ordering': ['-date_alerte'],
                'indexes': [models.Index(fields=['licence', 'envoyee'], name='licences_li_licence_401f3e_idx'), models.Index(fields=['type_alerte', 'date_alerte'], name='licences_li_type_al_a30b4d_idx')],
            },
        ),
        migrations.CreateModel(
            name='LicenceActivation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('mac_address', models.CharField(help_text='Adresse MAC unique du serveur', max_length=17, verbose_name='Adresse MAC')),
                ('hostname', models.CharField(help_text='Nom DNS du serveur', max_length=255, verbose_name="Nom d'hôte")),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="Adresse IP du serveur au moment de l'activation", null=True, verbose_name='Adresse IP')),
                ('mode_activation', models.CharField(choices=[('ONLINE', '🌐 Online - Activation en ligne'), ('OFFLINE', '📴 Offline - Activation par fichier')], default='ONLINE', max_length=10, verbose_name="Mode d'activation")),
                ('user_agent', models.CharField(blank=True, default='', help_text='Informations sur le navigateur/système', max_length=500, verbose_name='User Agent')),
                ('est_active', models.BooleanField(default=True, help_text="False si l'activation a été révoquée", verbose_name='Activation active')),
                ('date_revocation', models.DateTimeField(blank=True, null=True, verbose_name='Date de révocation')),
                ('licence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='licences.licence', verbose_name='Licence')),
            ],
            options={
                'verbose_name': 'Activation de licence',
                'verbose_name_plural': 'Activations de licence',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['licence', 'est_active'], name='licences_li_licence_c6f47d_idx'), models.Index(fields=['mac_address', 'hostname'], name='licences_li_mac_add_30f901_idx')],
                'unique_together': {('licence', 'mac_address', 'hostname')},
            },
        ),
        migrations.AddIndex(
            model_name='licence',
            index=models.Index(fields=['cle_licence'], name='licences_li_cle_lic_4d8054_idx'),
        ),
        migrations.AddIndex(
            model_name='licence',
            index=models.Index(fields=['statut', 'date_expiration'], name='licences_li_statut_b7d529_idx'),
        ),
    ]
