# Generated by Django 5.2 — licence commerciale signée hors ligne

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0003_licence_created_by_licence_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licence',
            name='signature_ed25519',
            field=models.CharField(
                blank=True,
                default='',
                editable=False,
                help_text="Signature du fournisseur ; la clé privée reste hors installation",
                max_length=128,
                verbose_name='Signature Ed25519',
            ),
        ),
        migrations.AddField(
            model_name='licence',
            name='signed_payload',
            field=models.JSONField(
                blank=True,
                default=dict,
                editable=False,
                help_text="Données commerciales signées par l'éditeur",
                verbose_name='Payload de licence signé',
            ),
        ),
        migrations.AlterField(
            model_name='licence',
            name='signature_hmac',
            field=models.CharField(
                editable=False,
                help_text='Ancienne signature conservée pour migration uniquement',
                max_length=64,
                verbose_name='Signature HMAC historique',
            ),
        ),
    ]
