# Generated by Django 4.2.29 on 2026-09-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0003_licence_created_by_licence_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licence',
            name='signature_ed25519',
            field=models.CharField(blank=True, default='', editable=False, help_text='Signature asymétrique Ed25519 — clé privée chez éditeur, publique dans app', max_length=128, verbose_name='Signature Ed25519'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='signature_hmac',
            field=models.CharField(editable=False, help_text='Signature cryptographique legacy (HMAC-SHA256) — conservée pour transition', max_length=64, verbose_name='Signature HMAC'),
        ),
    ]
