# Generated by Django 4.2.29 on 2026-09-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0004_p1_ed25519_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='licence',
            name='bail_offline_expire_le',
            field=models.DateTimeField(blank=True, help_text="Date d'expiration du bail offline (fenêtre décroissante)", null=True, verbose_name='Bail offline expire le'),
        ),
        migrations.AddField(
            model_name='licence',
            name='dernier_heartbeat',
            field=models.DateTimeField(blank=True, help_text='Date du dernier heartbeat réussi vers serveur éditeur', null=True, verbose_name='Dernier heartbeat'),
        ),
        migrations.AddField(
            model_name='licence',
            name='heartbeat_failures',
            field=models.IntegerField(default=0, help_text="Nombre d'échecs heartbeat consécutifs", verbose_name='Échecs heartbeat consécutifs'),
        ),
        migrations.AddField(
            model_name='licence',
            name='heartbeat_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Payload signé du dernier heartbeat (debug)', verbose_name='Dernier payload heartbeat'),
        ),
        migrations.AddField(
            model_name='licenceactivation',
            name='cpu_id',
            field=models.CharField(blank=True, default='', help_text='Identifiant CPU (optionnel, renforce binding)', max_length=255, verbose_name='CPU ID'),
        ),
        migrations.AddField(
            model_name='licenceactivation',
            name='disk_serial',
            field=models.CharField(blank=True, default='', help_text='Numéro de série disque système', max_length=255, verbose_name='Numéro série disque'),
        ),
        migrations.AddField(
            model_name='licenceactivation',
            name='fingerprint_signature',
            field=models.CharField(blank=True, default='', help_text="HMAC-SHA256 de l'empreinte, ou Ed25519 hex", max_length=256, verbose_name='Signature empreinte'),
        ),
        migrations.AddField(
            model_name='licenceactivation',
            name='fingerprint_signature_ed25519',
            field=models.CharField(blank=True, default='', help_text="Signature Ed25519 de l'empreinte (clé privée éditeur)", max_length=128, verbose_name='Signature empreinte Ed25519'),
        ),
        migrations.AddField(
            model_name='licenceactivation',
            name='machine_fingerprint',
            field=models.CharField(blank=True, default='', help_text='SHA256 canonique de MAC+hostname+CPU+disk+UUID+OS', max_length=64, verbose_name='Empreinte machine'),
        ),
        migrations.AddField(
            model_name='licenceactivation',
            name='os_info',
            field=models.CharField(blank=True, default='', help_text='Informations OS / platform', max_length=500, verbose_name='OS info'),
        ),
        migrations.AddField(
            model_name='licenceactivation',
            name='platform_data',
            field=models.JSONField(blank=True, default=dict, help_text='Attributs additionnels (arch, machine, etc.)', verbose_name='Données plateforme'),
        ),
        migrations.AddField(
            model_name='licenceactivation',
            name='system_uuid',
            field=models.CharField(blank=True, default='', help_text='UUID système (SMBIOS)', max_length=255, verbose_name='System UUID'),
        ),
        migrations.AddIndex(
            model_name='licenceactivation',
            index=models.Index(fields=['machine_fingerprint'], name='licences_li_machine_3da5f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='licenceactivation',
            constraint=models.UniqueConstraint(condition=models.Q(('est_active', True)), fields=('licence',), name='unique_active_activation_per_licence'),
        ),
    ]
