# Generated by Django 4.2.29 on 2026-05-08 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etablissements', '0004_groupe_etablissements'),
        ('parametres', '0025_declencheur_sms'),
        ('inscriptions', '0013_transfert_eleve'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageParent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('type', models.CharField(choices=[('CONVOCATION', 'Convocation à un entretien'), ('AVERTISSEMENT', 'Avertissement de comportement'), ('JUSTIFICATIF', "Demande de justificatif d'absence"), ('RELANCE', 'Relance de paiement')], max_length=20, verbose_name='Type')),
                ('objet', models.CharField(max_length=200, verbose_name='Objet')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token de réponse')),
                ('statut', models.CharField(choices=[('ENVOYE', 'Envoyé'), ('LU', 'Lu'), ('REPONDU', 'Répondu')], default='ENVOYE', max_length=20, verbose_name='Statut')),
                ('telephone_utilise', models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone')),
                ('creneaux_proposes', models.JSONField(blank=True, default=list, verbose_name='Créneaux proposés')),
                ('sms_envoye', models.BooleanField(default=False, verbose_name='SMS envoyé')),
                ('date_envoi_sms', models.DateTimeField(blank=True, null=True, verbose_name='Date envoi SMS')),
                ('annee_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametres.anneescolaire', verbose_name='Année scolaire')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_parents', to='inscriptions.eleve', verbose_name='Élève')),
                ('envoye_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL, verbose_name='Envoyé par')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_parents', to='etablissements.etablissement', verbose_name='Établissement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Message parent',
                'verbose_name_plural': 'Messages parents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReponseParent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('creneau_choisi', models.CharField(blank=True, default='', max_length=200, verbose_name='Créneau choisi')),
                ('accuse_reception', models.BooleanField(default=False, verbose_name='Accusé de réception')),
                ('date_reglement_prevue', models.DateField(blank=True, null=True, verbose_name='Date de règlement prévisionnelle')),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='communication/justificatifs/', verbose_name='Justificatif')),
                ('commentaire', models.TextField(blank=True, default='', verbose_name='Commentaire')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reponse', to='communication.messageparent', verbose_name='Message')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Réponse parent',
                'verbose_name_plural': 'Réponses parents',
            },
        ),
    ]
