# Generated by Django 4.2.29 on 2026-06-01 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0013_transfert_eleve'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingSMSLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('sender_number', models.CharField(max_length=20, verbose_name='Numéro émetteur')),
                ('message_text', models.TextField(verbose_name='Texte du SMS')),
                ('command_type', models.CharField(choices=[('NOTE', 'Demande de note/moyenne'), ('SOLDE', 'Demande de solde financier'), ('ABS', "Demande de relevé d'absences"), ('HELP', 'Aide / Instructions'), ('INVALID', 'Commande invalide ou inconnue')], default='INVALID', max_length=10, verbose_name='Type de commande')),
                ('response_text', models.TextField(blank=True, default='', verbose_name='Réponse envoyée')),
                ('is_authorized', models.BooleanField(default=False, verbose_name='Autorisé')),
                ('processed_successfully', models.BooleanField(default=False, verbose_name='Traité avec succès')),
                ('error_message', models.TextField(blank=True, default='', verbose_name="Message d'erreur")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('eleve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_sms', to='inscriptions.eleve', verbose_name='Élève concerné')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'SMS Entrant',
                'verbose_name_plural': 'SMS Entrants',
                'ordering': ['-created_at'],
            },
        ),
    ]
