# Generated by Django 4.2.29 on 2026-09-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_incomingsmslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageparent',
            name='date_expiration',
            field=models.DateTimeField(blank=True, help_text="Au-delà, le lien public /repondre/ affiche 'lien expiré'.", null=True, verbose_name="Date d'expiration du lien"),
        ),
    ]
