# Generated by Django 4.2.29 on 2026-03-31 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscriptions', '0010_alter_inscription_statut'),
        ('pedagogie', '0006_add_dispense_to_resultat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('absences_justifiees', models.PositiveIntegerField(default=0, verbose_name='Absences justifiées (heures)')),
                ('absences_non_justifiees', models.PositiveIntegerField(default=0, verbose_name='Absences non justifiées (heures)')),
                ('retards', models.PositiveIntegerField(default=0, verbose_name='Retards')),
                ('appreciation_conseil', models.TextField(blank=True, default='', help_text='Observation saisie lors du conseil de classe', verbose_name='Appréciation du conseil de classe')),
                ('est_publie', models.BooleanField(default=False, help_text='Un bulletin publié est visible par les parents / élèves', verbose_name='Publié')),
                ('date_publication', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='inscriptions.inscription', verbose_name='Inscription')),
                ('publie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins_publies', to=settings.AUTH_USER_MODEL, verbose_name='Publié par')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='pedagogie.trimestre', verbose_name='Trimestre')),
            ],
            options={
                'verbose_name': 'Bulletin',
                'verbose_name_plural': 'Bulletins',
                'ordering': ['trimestre__numero', 'inscription__eleve__nom', 'inscription__eleve__prenom'],
                'unique_together': {('inscription', 'trimestre')},
            },
        ),
    ]
