# Generated by Django 4.2.29 on 2026-04-28 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0025_declencheur_sms'),
        ('inscriptions', '0013_transfert_eleve'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bulletins', '0002_bulletin_created_by_bulletin_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinAnnuel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('donnees_json', models.JSONField(default=dict, help_text='JSON contenant les moyennes par période', verbose_name='Données du bulletin')),
                ('moyenne_annuelle', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Moyenne annuelle')),
                ('est_admis', models.BooleanField(default=False, help_text='True si moyenne_annuelle >= 10.00', verbose_name='Admis')),
                ('genere_le', models.DateTimeField(auto_now=True, verbose_name='Généré le')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins_annuels', to='parametres.anneescolaire', verbose_name='Année scolaire')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins_annuels', to='inscriptions.inscription', verbose_name='Inscription')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Bulletin annuel',
                'verbose_name_plural': 'Bulletins annuels',
                'ordering': ['inscription__eleve__nom', 'inscription__eleve__prenom'],
                'unique_together': {('inscription', 'annee_scolaire')},
            },
        ),
    ]
