# Generated by Django 4.2.29 on 2026-04-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0003_bulletin_annuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinannuel',
            name='appreciation_conseil',
            field=models.TextField(blank=True, default='', verbose_name='Appréciation du conseil de classe'),
        ),
        migrations.AddField(
            model_name='bulletinannuel',
            name='date_signature',
            field=models.DateField(blank=True, null=True, verbose_name='Date de signature'),
        ),
        migrations.AddField(
            model_name='bulletinannuel',
            name='effectif_classe',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Effectif de la classe'),
        ),
        migrations.AddField(
            model_name='bulletinannuel',
            name='lieu_signature',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Lieu de signature'),
        ),
        migrations.AddField(
            model_name='bulletinannuel',
            name='moyenne_classe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Moyenne de la classe'),
        ),
        migrations.AddField(
            model_name='bulletinannuel',
            name='moyenne_max_classe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Plus forte moyenne de la classe'),
        ),
        migrations.AddField(
            model_name='bulletinannuel',
            name='moyenne_min_classe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Plus faible moyenne de la classe'),
        ),
        migrations.AddField(
            model_name='bulletinannuel',
            name='rang_annuel',
            field=models.PositiveIntegerField(blank=True, help_text="Rang de l'élève basé sur la moyenne annuelle", null=True, verbose_name='Rang annuel'),
        ),
    ]
