# Generated by Django 4.2.29 on 2026-05-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0004_bulletinannuel_appreciation_conseil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='signe_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Signé le'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='signe_par_nom',
            field=models.CharField(blank=True, max_length=100, verbose_name='Signé par'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='token_expire_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Token valide jusqu'au"),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='token_signature',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Token de signature'),
        ),
    ]
