# Generated by Django 4.2.29 on 2026-03-12 13:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscriptions', '0001_initial'),
        ('parametres', '0002_typedocument_data'),
        ('etablissements', '0001_initial'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionExamen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('type_examen', models.CharField(choices=[('CEP', "CEP — Certificat d'Études Primaires"), ('BEPC', 'BEPC — Brevet du Premier Cycle'), ('BAC', 'BAC — Baccalauréat'), ('AUTRES', 'Autre examen')], max_length=10, verbose_name="Type d'examen")),
                ('libelle', models.CharField(help_text='Ex: CEP 2025-2026, BEPC Session 2026', max_length=100, verbose_name='Libellé')),
                ('date_debut', models.DateField(verbose_name='Date de début des épreuves')),
                ('date_fin', models.DateField(verbose_name='Date de fin des épreuves')),
                ('date_deliberation', models.DateField(blank=True, null=True, verbose_name='Date de délibération')),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('DELIBEREE', 'Délibérée')], default='PLANIFIEE', max_length=15, verbose_name='Statut')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observations')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_examen', to='parametres.anneescolaire', verbose_name='Année scolaire')),
            ],
            options={
                'verbose_name': "Session d'Examen",
                'verbose_name_plural': "Sessions d'Examens",
                'ordering': ['-date_debut'],
                'unique_together': {('annee_scolaire', 'type_examen')},
            },
        ),
        migrations.CreateModel(
            name='CentreExamen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('nom', models.CharField(help_text="Ex: Centre CEP de l'École A de Koudougou", max_length=200, verbose_name='Nom du centre')),
                ('code_centre', models.CharField(max_length=20, verbose_name='Code du centre')),
                ('adresse', models.TextField(blank=True, default='', verbose_name='Adresse')),
                ('capacite', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Capacité d'accueil")),
                ('etablissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centres_examen', to='etablissements.etablissement', verbose_name='Établissement hôte')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centres', to='examens.sessionexamen', verbose_name='Session')),
            ],
            options={
                'verbose_name': "Centre d'Examen",
                'verbose_name_plural': "Centres d'Examens",
                'ordering': ['session', 'code_centre'],
                'unique_together': {('session', 'code_centre')},
            },
        ),
        migrations.CreateModel(
            name='SalleExamen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('nom', models.CharField(help_text='Ex: Salle A, Salle 01, Amphithéâtre', max_length=50, verbose_name='Nom/numéro de salle')),
                ('capacite', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacité')),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles', to='examens.centreexamen', verbose_name='Centre')),
                ('surveillant_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salles_surveillees', to='personnel.membrepersonnel', verbose_name='Surveillant principal')),
            ],
            options={
                'verbose_name': "Salle d'Examen",
                'verbose_name_plural': "Salles d'Examen",
                'ordering': ['centre', 'nom'],
                'unique_together': {('centre', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='InscriptionExamen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('numero_table', models.CharField(blank=True, default='', help_text="Numéro attribué au candidat pour l'examen", max_length=20, verbose_name='Numéro de table')),
                ('statut', models.CharField(choices=[('INSCRIT', 'Inscrit'), ('ADMIS', 'Admis'), ('AJOURNE', 'Ajourné'), ('ABSENT', 'Absent le jour J'), ('EXCLU', 'Exclu')], default='INSCRIT', max_length=10, verbose_name='Statut')),
                ('moyenne_examen', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Moyenne à l'examen")),
                ('mention', models.CharField(blank=True, default='', help_text='Ex: Passable, Assez Bien, Bien, Très Bien', max_length=50, verbose_name='Mention')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observations')),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidats', to='examens.centreexamen', verbose_name="Centre d'affectation")),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_examen', to='inscriptions.inscription', verbose_name='Inscription scolaire')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_examen', to='examens.sessionexamen', verbose_name='Session')),
            ],
            options={
                'verbose_name': "Inscription à l'Examen",
                'verbose_name_plural': 'Inscriptions aux Examens',
                'ordering': ['session', 'numero_table'],
                'unique_together': {('session', 'inscription')},
            },
        ),
    ]
