# Generated by Django 4.2.29 on 2026-05-08 00:59

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inscriptions', '0013_transfert_eleve'),
        ('etablissements', '0004_groupe_etablissements'),
        ('pedagogie', '0011_competences'),
        ('parametres', '0025_declencheur_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManuelScolaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('auteur', models.CharField(blank=True, default='', max_length=200, verbose_name='Auteur')),
                ('editeur', models.CharField(blank=True, default='', max_length=200, verbose_name='Éditeur')),
                ('isbn', models.CharField(blank=True, default='', max_length=20, verbose_name='ISBN')),
                ('cycle', models.CharField(choices=[('PRESCOLAIRE', 'Préscolaire'), ('PRIMAIRE', 'Primaire'), ('POST_PRIMAIRE', 'Post-primaire'), ('SECONDAIRE', 'Secondaire')], max_length=20, verbose_name='Cycle')),
                ('annee_edition', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Année d'édition")),
                ('prix_remplacement', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text="Facturé à l'élève si le manuel n'est pas rendu.", max_digits=10, verbose_name='Prix de remplacement (FCFA)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manuels', to='parametres.classe', verbose_name='Classe (facultatif)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuels', to='etablissements.etablissement')),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manuels', to='pedagogie.matiere', verbose_name='Matière')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Manuel scolaire',
                'verbose_name_plural': 'Manuels scolaires',
                'ordering': ['cycle', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='ExemplaireManuel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('code_exemplaire', models.CharField(max_length=15, unique=True, verbose_name='Code exemplaire')),
                ('etat', models.CharField(choices=[('NEUF', 'Neuf'), ('BON', 'Bon état'), ('USAGE', 'Usagé'), ('DETERIORE', 'Détérioré')], default='NEUF', max_length=10, verbose_name='État')),
                ('annee_acquisition', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Année d'acquisition")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('manuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplaires', to='manuels.manuelscolaire')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Exemplaire',
                'verbose_name_plural': 'Exemplaires',
                'ordering': ['code_exemplaire'],
            },
        ),
        migrations.CreateModel(
            name='AttributionManuel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('date_attribution', models.DateField(verbose_name="Date d'attribution")),
                ('etat_sortie', models.CharField(choices=[('NEUF', 'Neuf'), ('BON', 'Bon état'), ('USAGE', 'Usagé'), ('DETERIORE', 'Détérioré')], default='BON', max_length=10, verbose_name='État à la sortie')),
                ('date_retour', models.DateField(blank=True, null=True, verbose_name='Date de retour')),
                ('etat_retour', models.CharField(blank=True, choices=[('NEUF', 'Neuf'), ('BON', 'Bon état'), ('USAGE', 'Usagé'), ('DETERIORE', 'Détérioré')], default='', max_length=10, verbose_name='État au retour')),
                ('facture_genere', models.BooleanField(default=False, help_text="Vrai si la pénalité de non-retour a été ajoutée aux frais de l'élève.", verbose_name='Frais facturés')),
                ('observation', models.TextField(blank=True, default='', verbose_name='Observation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='manuels.exemplairemanuel')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions_manuels', to='inscriptions.inscription')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Attribution de manuel',
                'verbose_name_plural': 'Attributions de manuels',
                'ordering': ['-date_attribution'],
            },
        ),
    ]
