# Generated by Django 5.2.17 on 2026-09-16 02:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0004_groupe_etablissements'),
        ('inscriptions', '0014_alter_eleve_matricule'),
        ('manuels', '0001_initial'),
        ('parametres', '0025_declencheur_sms'),
        ('pedagogie', '0012_ajout_categorie_competence_apc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attributionmanuel',
            constraint=models.UniqueConstraint(condition=models.Q(('date_retour__isnull', True)), fields=('exemplaire',), name='manuel_exemplaire_non_rendu_unique'),
        ),
        migrations.AddConstraint(
            model_name='manuelscolaire',
            constraint=models.CheckConstraint(condition=models.Q(('prix_remplacement__gte', 0)), name='manuel_prix_non_negatif'),
        ),
    ]
