# Generated by Django 4.2.29 on 2026-03-12 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametres', '0002_typedocument_data'),
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant Versé')),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('VIREMENT', 'Virement Bancaire'), ('MOBILE_MONEY', 'Mobile Money'), ('CHEQUE', 'Chèque')], default='ESPECES', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence Transaction')),
                ('observation', models.TextField(blank=True)),
                ('encaisse_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='inscriptions.inscription')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Echeancier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('libelle', models.CharField(max_length=100)),
                ('date_limite', models.DateField()),
                ('montant_du', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paye', models.BooleanField(default=False)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeancier', to='inscriptions.inscription')),
            ],
            options={
                'verbose_name': 'Échéance de paiement',
                'verbose_name_plural': 'Échéancier',
                'ordering': ['date_limite'],
            },
        ),
        migrations.CreateModel(
            name='FraisScolarite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('cycle', models.CharField(blank=True, choices=[('PRESCOLAIRE', 'Préscolaire'), ('PRIMAIRE', 'Primaire'), ('POST-PRIMAIRE', 'Post-primaire'), ('SECONDAIRE', 'Secondaire')], max_length=20, null=True)),
                ('type_frais', models.CharField(choices=[('SCOLARITE', 'Scolarité'), ('INSCRIPTION', 'Inscription'), ('EXAMEN', "Frais d'examen"), ('AUTRE', 'Autre')], default='SCOLARITE', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (FCFA)')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.anneescolaire', verbose_name='Année Scolaire')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametres.classe', verbose_name='Classe')),
            ],
            options={
                'verbose_name': 'Frais de Scolarité',
                'verbose_name_plural': 'Frais de Scolarité',
                'unique_together': {('annee_scolaire', 'classe', 'type_frais')},
            },
        ),
    ]
