# Generated by Django 4.2.29 on 2026-03-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraisscolarite',
            name='cycle',
            field=models.CharField(blank=True, choices=[('PRESCOLAIRE', 'Préscolaire'), ('PRIMAIRE', 'Primaire'), ('POST_PRIMAIRE', 'Post-primaire'), ('SECONDAIRE', 'Secondaire')], max_length=20, null=True),
        ),
    ]
