# Generated by Django 4.2.29 on 2026-03-13 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0008_typesanction'),
        ('finances', '0002_alter_fraisscolarite_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='rubrique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametres.rubriquepaiement', verbose_name='Rubrique de paiement'),
        ),
    ]
