# Generated by Django 4.2.29 on 2026-03-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_add_rubrique_to_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='echeance',
            field=models.DateField(blank=True, null=True, verbose_name='Échéance'),
        ),
    ]
