# Generated by Django 4.2.29 on 2026-03-14 00:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_add_echeance_to_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateField(default=datetime.date.today, verbose_name='Date de transaction'),
        ),
    ]
