# Generated by Django 4.2.29 on 2026-03-24 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0018_alter_signatairedocument_fonction_and_more'),
        ('finances', '0005_date_paiement_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='statut_eleve',
            field=models.ForeignKey(blank=True, help_text="Statut de l'élève tel qu'il était au moment du versement", null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametres.statuteleve', verbose_name='Statut élève au paiement'),
        ),
    ]
