# Generated by Django 4.2.29 on 2026-04-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_echeancier_created_by_echeancier_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='numero_recu',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Numéro de reçu'),
        ),
    ]
