# Generated by Django 4.2.29 on 2026-04-04 22:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0003_etablissement_created_by_etablissement_updated_by_and_more'),
        ('inscriptions', '0011_eleve_created_by_eleve_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametres', '0022_add_modele_message'),
        ('finances', '0010_historiquerelance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquerelance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='historiquerelance',
            name='envoye_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Envoyé par'),
        ),
        migrations.AlterField(
            model_name='historiquerelance',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='historiquerelance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='historiquerelance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.CreateModel(
            name='TypeBourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('source', models.CharField(choices=[('ETAT', 'État / Gouvernement'), ('ONG', 'ONG / Organisation internationale'), ('ETABLISSEMENT', 'Établissement'), ('AUTRE', 'Autre')], default='ETABLISSEMENT', max_length=20, verbose_name='Source')),
                ('type_reduction', models.CharField(choices=[('POURCENTAGE', 'Pourcentage (%)'), ('MONTANT_FIXE', 'Montant fixe (FCFA)')], default='POURCENTAGE', max_length=20, verbose_name='Type de réduction')),
                ('valeur_reduction', models.DecimalField(decimal_places=2, help_text='Pourcentage (ex: 50) ou montant fixe (ex: 25000)', max_digits=8, verbose_name='Valeur de la réduction')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_bourses', to='etablissements.etablissement', verbose_name='Établissement')),
                ('rubrique', models.ForeignKey(blank=True, help_text='Laisser vide pour appliquer sur le total toutes rubriques', null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametres.rubriquepaiement', verbose_name='Rubrique concernée')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Type de bourse',
                'verbose_name_plural': 'Types de bourses',
                'ordering': ['nom'],
                'unique_together': {('etablissement', 'code')},
            },
        ),
        migrations.CreateModel(
            name='BourseEleve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('montant_accorde', models.DecimalField(decimal_places=2, help_text='Calculé automatiquement à partir du type; peut être modifié', max_digits=12, verbose_name='Montant accordé (FCFA)')),
                ('date_attribution', models.DateField(default=datetime.date.today, verbose_name="Date d'attribution")),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('reference_document', models.CharField(blank=True, max_length=100, verbose_name='Référence / N° décision')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('attribue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Attribué par')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bourses', to='inscriptions.inscription', verbose_name='Inscription')),
                ('rubrique', models.ForeignKey(blank=True, help_text='Laisser vide pour réduction globale sur le total dû', null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametres.rubriquepaiement', verbose_name='Rubrique ciblée')),
                ('type_bourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='finances.typebourse', verbose_name='Type de bourse')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Bourse / Aide scolaire',
                'verbose_name_plural': 'Bourses / Aides scolaires',
                'ordering': ['-date_attribution'],
            },
        ),
    ]
