# Generated by Django 4.2.29 on 2026-05-03 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametres', '0025_declencheur_sms'),
        ('inscriptions', '0013_transfert_eleve'),
        ('finances', '0011_add_bourse_eleve'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandePaiementMobile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (FCFA)')),
                ('telephone', models.CharField(max_length=20, verbose_name='Numéro Orange Money')),
                ('reference', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Référence MM')),
                ('token', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Token de confirmation')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('confirme_le', models.DateTimeField(blank=True, null=True, verbose_name='Confirmé le')),
                ('sms_envoye', models.BooleanField(default=False, verbose_name='SMS envoyé')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('confirme_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmations_mobile', to=settings.AUTH_USER_MODEL, verbose_name='Confirmé par')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_mobile_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_mobile', to='inscriptions.inscription', verbose_name='Inscription')),
                ('paiement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_mobile', to='finances.paiement', verbose_name='Paiement généré')),
                ('rubrique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametres.rubriquepaiement', verbose_name='Rubrique de paiement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Demande paiement Mobile Money',
                'verbose_name_plural': 'Demandes paiement Mobile Money',
                'ordering': ['-created_at'],
            },
        ),
    ]
