# Generated by Django 4.2.29 on 2026-05-08 00:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etablissements', '0004_groupe_etablissements'),
        ('parametres', '0025_declencheur_sms'),
        ('finances', '0012_demande_paiement_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieDepense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('type_depense', models.CharField(choices=[('SALAIRES', 'Salaires et charges'), ('FOURNITURES', 'Fournitures et matériel'), ('MAINTENANCE', 'Maintenance et réparations'), ('UTILITIES', 'Eau, électricité, internet'), ('COMMUNICATION', 'Communication et publicité'), ('TRANSPORT', 'Transport et déplacements'), ('FORMATION', 'Formation du personnel'), ('AUTRE', 'Autres dépenses')], default='AUTRE', max_length=20, verbose_name='Type')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_depenses', to='etablissements.etablissement', verbose_name='Établissement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Catégorie de dépense',
                'verbose_name_plural': 'Catégories de dépenses',
                'ordering': ['type_depense', 'nom'],
                'unique_together': {('etablissement', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('numero_depense', models.CharField(blank=True, max_length=20, unique=True, verbose_name='N° dépense')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant (FCFA)')),
                ('date_depense', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('VIREMENT', 'Virement Bancaire'), ('MOBILE_MONEY', 'Mobile Money'), ('CHEQUE', 'Chèque')], default='ESPECES', max_length=20, verbose_name='Mode de paiement')),
                ('beneficiaire', models.CharField(blank=True, max_length=200, verbose_name='Bénéficiaire')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence / N° pièce')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_validation', models.DateField(blank=True, null=True, verbose_name='Date de validation')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='parametres.anneescolaire', verbose_name='Année scolaire')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='finances.categoriedepense', verbose_name='Catégorie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('saisi_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_saisies', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_depense', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAnnuel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver sans supprimer.', verbose_name='Actif')),
                ('montant_prevu', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant prévu (FCFA)')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='parametres.anneescolaire', verbose_name='Année scolaire')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finances.categoriedepense', verbose_name='Catégorie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Budget annuel',
                'verbose_name_plural': 'Budgets annuels',
                'ordering': ['categorie__type_depense', 'categorie__nom'],
                'unique_together': {('annee_scolaire', 'categorie')},
            },
        ),
    ]
