# Generated by Django 5.2.17 on 2026-09-16 01:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0014_depense_motif_annulation'),
        ('inscriptions', '0014_alter_eleve_matricule'),
        ('parametres', '0025_declencheur_sms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bourseeleve',
            constraint=models.CheckConstraint(condition=models.Q(('montant_accorde__gt', 0)), name='bourse_montant_positif'),
        ),
        migrations.AddConstraint(
            model_name='budgetannuel',
            constraint=models.CheckConstraint(condition=models.Q(('montant_prevu__gte', 0)), name='budget_montant_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='demandepaiementmobile',
            constraint=models.CheckConstraint(condition=models.Q(('montant__gt', 0)), name='mobile_money_montant_positif'),
        ),
        migrations.AddConstraint(
            model_name='depense',
            constraint=models.CheckConstraint(condition=models.Q(('montant__gt', 0)), name='depense_montant_positif'),
        ),
        migrations.AddConstraint(
            model_name='echeancier',
            constraint=models.CheckConstraint(condition=models.Q(('montant_du__gt', 0)), name='echeancier_montant_positif'),
        ),
        migrations.AddConstraint(
            model_name='fraisscolarite',
            constraint=models.CheckConstraint(condition=models.Q(('montant__gt', 0)), name='frais_montant_positif'),
        ),
        migrations.AddConstraint(
            model_name='historiquerelance',
            constraint=models.CheckConstraint(condition=models.Q(('montant_reclame__gt', 0)), name='relance_montant_positif'),
        ),
        migrations.AddConstraint(
            model_name='paiement',
            constraint=models.CheckConstraint(condition=models.Q(('montant__gt', 0)), name='paiement_montant_positif'),
        ),
        migrations.AddConstraint(
            model_name='remboursement',
            constraint=models.CheckConstraint(condition=models.Q(('montant__gt', 0)), name='remboursement_montant_positif'),
        ),
    ]
